// Auto-generated by generate_classification_data.py
// Text classification data for KupasAI NLP Week 7

const CLASSIFICATION_DATA = {
  "sample_texts": [
    {
      "text": "Film ini sangat bagus dan menarik",
      "label": "positif",
      "tokens": [
        "film",
        "ini",
        "sangat",
        "bagus",
        "dan",
        "menarik"
      ]
    },
    {
      "text": "Pelayanan toko sangat mengecewakan",
      "label": "negatif",
      "tokens": [
        "pelayanan",
        "toko",
        "sangat",
        "mengecewakan"
      ]
    },
    {
      "text": "Produk berkualitas dengan harga terjangkau",
      "label": "positif",
      "tokens": [
        "produk",
        "berkualitas",
        "dengan",
        "harga",
        "terjangkau"
      ]
    },
    {
      "text": "Barang rusak dan tidak sesuai deskripsi",
      "label": "negatif",
      "tokens": [
        "barang",
        "rusak",
        "dan",
        "tidak",
        "sesuai",
        "deskripsi"
      ]
    }
  ],
  "pipeline_steps": [
    {
      "title": "Teks Mentah",
      "desc": "Input mentah dari pengguna. Bisa berupa review produk, komentar media sosial, email, atau dokumen apapun.",
      "example": "Film ini sangat bagus dan menarik"
    },
    {
      "title": "Preprocessing",
      "desc": "Teks dibersihkan: lowercasing, hapus tanda baca, tokenisasi, hapus stopwords (kata-kata seperti 'dan', 'ini', 'yang').",
      "example": "[film, sangat, bagus, menarik]"
    },
    {
      "title": "Vektorisasi",
      "desc": "Token dikonversi menjadi vektor numerik. Metode sederhana: Bag-of-Words (frekuensi kata). Metode lanjutan: TF-IDF atau word embeddings dari model pre-trained.",
      "example": "[0, 0, 2, 1, 0, 0, 1, 1, 0, ...]"
    },
    {
      "title": "Klasifikasi",
      "desc": "Vektor dimasukkan ke model classifier (Naive Bayes, SVM, Logistic Regression, atau Neural Network). Model menghasilkan skor untuk setiap kelas.",
      "example": "positif: 0.87, negatif: 0.13"
    },
    {
      "title": "Output",
      "desc": "Kelas dengan skor tertinggi menjadi prediksi akhir. Skor (confidence) menunjukkan seberapa yakin model dengan prediksinya.",
      "example": "Prediksi: POSITIF (87%)"
    }
  ],
  "boundary_points": [
    {
      "x": 0.4,
      "y": 0.285,
      "label": "positif"
    },
    {
      "x": 0.686,
      "y": 0.18,
      "label": "positif"
    },
    {
      "x": 0.225,
      "y": 0.047,
      "label": "positif"
    },
    {
      "x": 0.146,
      "y": 0.26,
      "label": "positif"
    },
    {
      "x": 0.581,
      "y": 0.212,
      "label": "positif"
    },
    {
      "x": 0.116,
      "y": 0.291,
      "label": "positif"
    },
    {
      "x": 0.766,
      "y": 0.064,
      "label": "positif"
    },
    {
      "x": 0.245,
      "y": 0.055,
      "label": "positif"
    },
    {
      "x": 0.343,
      "y": 0.157,
      "label": "positif"
    },
    {
      "x": 0.446,
      "y": 0.087,
      "label": "positif"
    },
    {
      "x": 0.589,
      "y": 0.042,
      "label": "positif"
    },
    {
      "x": 0.334,
      "y": 0.11,
      "label": "positif"
    },
    {
      "x": 0.465,
      "y": 0.236,
      "label": "positif"
    },
    {
      "x": 0.26,
      "y": 0.154,
      "label": "positif"
    },
    {
      "x": 0.574,
      "y": 0.014,
      "label": "positif"
    },
    {
      "x": 0.586,
      "y": 0.051,
      "label": "positif"
    },
    {
      "x": 0.152,
      "y": 0.285,
      "label": "positif"
    },
    {
      "x": 0.873,
      "y": 0.243,
      "label": "positif"
    },
    {
      "x": 0.344,
      "y": 0.029,
      "label": "positif"
    },
    {
      "x": 0.647,
      "y": 0.132,
      "label": "positif"
    },
    {
      "x": 0.037,
      "y": 0.496,
      "label": "negatif"
    },
    {
      "x": 0.01,
      "y": 0.827,
      "label": "negatif"
    },
    {
      "x": 0.078,
      "y": 0.63,
      "label": "negatif"
    },
    {
      "x": 0.094,
      "y": 0.516,
      "label": "negatif"
    },
    {
      "x": 0.164,
      "y": 0.248,
      "label": "negatif"
    },
    {
      "x": 0.291,
      "y": 0.72,
      "label": "negatif"
    },
    {
      "x": 0.282,
      "y": 0.816,
      "label": "negatif"
    },
    {
      "x": 0.179,
      "y": 0.837,
      "label": "negatif"
    },
    {
      "x": 0.027,
      "y": 0.257,
      "label": "negatif"
    },
    {
      "x": 0.014,
      "y": 0.36,
      "label": "negatif"
    },
    {
      "x": 0.117,
      "y": 0.317,
      "label": "negatif"
    },
    {
      "x": 0.249,
      "y": 0.385,
      "label": "negatif"
    },
    {
      "x": 0.084,
      "y": 0.534,
      "label": "negatif"
    },
    {
      "x": 0.042,
      "y": 0.742,
      "label": "negatif"
    },
    {
      "x": 0.022,
      "y": 0.89,
      "label": "negatif"
    },
    {
      "x": 0.232,
      "y": 0.259,
      "label": "negatif"
    },
    {
      "x": 0.002,
      "y": 0.752,
      "label": "negatif"
    },
    {
      "x": 0.212,
      "y": 0.683,
      "label": "negatif"
    },
    {
      "x": 0.231,
      "y": 0.159,
      "label": "negatif"
    },
    {
      "x": 0.108,
      "y": 0.193,
      "label": "negatif"
    },
    {
      "x": 0.559,
      "y": 0.487,
      "label": "negatif"
    },
    {
      "x": 0.319,
      "y": 0.393,
      "label": "negatif"
    },
    {
      "x": 0.519,
      "y": 0.491,
      "label": "positif"
    },
    {
      "x": 0.442,
      "y": 0.336,
      "label": "positif"
    },
    {
      "x": 0.528,
      "y": 0.468,
      "label": "positif"
    },
    {
      "x": 0.448,
      "y": 0.457,
      "label": "negatif"
    },
    {
      "x": 0.308,
      "y": 0.332,
      "label": "negatif"
    },
    {
      "x": 0.491,
      "y": 0.394,
      "label": "positif"
    }
  ],
  "classifiers": {
    "logistic": {
      "name": "Logistic Regression",
      "desc": "Garis lurus (linear) memisahkan kelas positif dan negatif. Cepat, interpretable, tapi terbatas untuk data yang tidak terpisah secara linear.",
      "boundary": {
        "type": "linear",
        "a": -1.0,
        "b": 0.85,
        "c": 0
      }
    },
    "naive_bayes": {
      "name": "Naive Bayes",
      "desc": "Berdasarkan teorema Bayes dengan asumsi independensi antar fitur. Probabilistik, cocok untuk text classification dasar, tapi asumsi independensi sering tidak terpenuhi.",
      "boundary": {
        "type": "linear",
        "a": -0.9,
        "b": 0.7,
        "c": 0.05
      }
    },
    "svm": {
      "name": "SVM (RBF Kernel)",
      "desc": "Support Vector Machine dengan kernel non-linear dapat membuat boundary melengkung. Lebih fleksibel dari logistic regression, tapi lebih lambat dan kurang interpretable.",
      "boundary": {
        "type": "rbf"
      }
    }
  },
  "bert_steps": [
    {
      "title": "Pre-trained BERT",
      "desc": "Mulai dari model BERT yang sudah pre-trained pada korpus besar (misal IndoBERT untuk Bahasa Indonesia). Model sudah memahami struktur bahasa, tapi belum dilatih untuk tugas klasifikasi spesifik.",
      "detail": "IndoBERT-base: 12 layer, 768 dim, 12 heads, dilatih pada ~220M kata Bahasa Indonesia"
    },
    {
      "title": "Tambah Classification Head",
      "desc": "Tambahkan satu lapis linear di atas output token [CLS]. Lapis ini memetakan representasi 768-dimensi BERT ke jumlah kelas (misal 2: positif/negatif). Hanya lapis ini yang awalnya random.",
      "detail": "Classifier: Linear(768, 2) + Softmax"
    },
    {
      "title": "Fine-tuning",
      "desc": "Latih seluruh model (BERT + classification head) pada dataset berlabel dengan learning rate kecil (2e-5). Backpropagation menyesuaikan semua bobot, tapi perlahan karena BERT sudah belajar representasi yang baik.",
      "detail": "Epoch: 3-5 | LR: 2e-5 | Batch size: 16-32"
    },
    {
      "title": "Evaluasi",
      "desc": "Uji model pada test set yang tidak dilihat selama training. Metrik: accuracy, precision, recall, F1-score. Confusion matrix menunjukkan distribusi prediksi vs label sebenarnya.",
      "detail": "Metrik: Accuracy, Precision, Recall, F1-Score, Confusion Matrix"
    }
  ],
  "confusion": {
    "labels": [
      "positif",
      "negatif"
    ],
    "matrix": [
      [
        42,
        5
      ],
      [
        3,
        38
      ]
    ],
    "total": 88,
    "accuracy": 0.909,
    "precision_pos": 0.933,
    "recall_pos": 0.894,
    "f1_pos": 0.913
  }
};
