// Generated by scripts/generate_advanced.py. Seed 42 unless specified.
var CNN_DATA = {
  "image": [
    [
      10,
      10,
      10,
      0,
      0,
      0
    ],
    [
      10,
      10,
      10,
      0,
      0,
      0
    ],
    [
      10,
      10,
      10,
      0,
      0,
      0
    ],
    [
      10,
      10,
      10,
      0,
      0,
      0
    ],
    [
      10,
      10,
      10,
      0,
      0,
      0
    ],
    [
      10,
      10,
      10,
      0,
      0,
      0
    ]
  ],
  "kernel": [
    [
      1,
      0,
      -1
    ],
    [
      1,
      0,
      -1
    ],
    [
      1,
      0,
      -1
    ]
  ],
  "architecture": [
    {
      "layer": "Conv2D",
      "detail": "32 filter, 3&times;3, ReLU",
      "note": "input 28&times;28&times;1"
    },
    {
      "layer": "MaxPooling2D",
      "detail": "pool 2&times;2",
      "note": "downsample fitur"
    },
    {
      "layer": "Conv2D",
      "detail": "64 filter, 3&times;3, ReLU",
      "note": "fitur lebih kompleks"
    },
    {
      "layer": "MaxPooling2D",
      "detail": "pool 2&times;2",
      "note": "downsample lagi"
    },
    {
      "layer": "Flatten",
      "detail": "ratakan ke vektor 1D",
      "note": ""
    },
    {
      "layer": "Dense",
      "detail": "64 neuron, ReLU",
      "note": "fully connected"
    },
    {
      "layer": "Dense",
      "detail": "10 neuron, Softmax",
      "note": "probabilitas 10 kelas (0-9)"
    }
  ],
  "featureMap": [
    [
      0,
      30,
      30,
      0
    ],
    [
      0,
      30,
      30,
      0
    ],
    [
      0,
      30,
      30,
      0
    ],
    [
      0,
      30,
      30,
      0
    ]
  ],
  "pooled": [
    [
      30,
      30
    ],
    [
      30,
      30
    ]
  ]
};
