// Generated by scripts/generate_advanced.py. Seed 42 unless specified.
var NL_DATA = {
  "deltaProp": {
    "delta2": 0.25,
    "weights12": [
      0,
      0.5,
      1,
      -1
    ]
  },
  "activations": {
    "relu": {
      "name": "ReLU",
      "formula": "f(x) = max(0, x)",
      "color": "#0969da"
    },
    "sigmoid": {
      "name": "Sigmoid",
      "formula": "f(x) = 1 / (1 + e^(&minus;x))",
      "color": "#8250df"
    },
    "tanh": {
      "name": "Tanh",
      "formula": "f(x) = tanh(x)",
      "color": "#1a7f37"
    }
  }
};
