// Auto-generated by generate_dt_data.py
// Decision Tree data for KupasAI ML Week 5 - toy 15-row example (Modul 5.1) + real decisiontree_ch6.csv

const DT_DATA = {
  "toy": {
    "rows": [
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "kelas": "sedan"
      },
      {
        "mesin": "bensin",
        "bangku": 2,
        "penggerak": "depan",
        "kelas": "sedan"
      },
      {
        "mesin": "bensin",
        "bangku": 8,
        "penggerak": "belakang",
        "kelas": "minibus"
      },
      {
        "mesin": "diesel",
        "bangku": 6,
        "penggerak": "depan",
        "kelas": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 5,
        "penggerak": "belakang",
        "kelas": "minibus"
      },
      {
        "mesin": "diesel",
        "bangku": 8,
        "penggerak": "belakang",
        "kelas": "minibus"
      },
      {
        "mesin": "diesel",
        "bangku": 8,
        "penggerak": "belakang",
        "kelas": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "kelas": "sedan"
      },
      {
        "mesin": "diesel",
        "bangku": 7,
        "penggerak": "belakang",
        "kelas": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "kelas": "sedan"
      },
      {
        "mesin": "bensin",
        "bangku": 2,
        "penggerak": "depan",
        "kelas": "sedan"
      },
      {
        "mesin": "diesel",
        "bangku": 6,
        "penggerak": "belakang",
        "kelas": "minibus"
      },
      {
        "mesin": "diesel",
        "bangku": 8,
        "penggerak": "depan",
        "kelas": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "kelas": "sedan"
      },
      {
        "mesin": "diesel",
        "bangku": 2,
        "penggerak": "depan",
        "kelas": "sedan"
      }
    ],
    "class_counts": {
      "minibus": 8,
      "sedan": 7
    },
    "entropy_total": 0.997,
    "splits": {
      "mesin": {
        "entropy_before": 0.997,
        "entropy_yes": 0.811,
        "entropy_no": 0.592,
        "n_yes": 8,
        "n_no": 7,
        "weighted": 0.709,
        "ig": 0.288
      },
      "penggerak": {
        "entropy_before": 0.997,
        "entropy_yes": 0.764,
        "entropy_no": 0.0,
        "n_yes": 9,
        "n_no": 6,
        "weighted": 0.459,
        "ig": 0.538
      },
      "bangku": {
        "entropy_before": 0.997,
        "entropy_yes": 0.0,
        "entropy_no": 0.544,
        "n_yes": 7,
        "n_no": 8,
        "weighted": 0.29,
        "ig": 0.707
      }
    }
  },
  "real": {
    "n_rows": 40,
    "accuracy": 1.0,
    "tree": {
      "samples": 32,
      "value": [
        18,
        14
      ],
      "predicted_class": "minibus",
      "impurity": 0.989,
      "feature": "bangku",
      "feature_display": "bangku",
      "threshold": 4.5,
      "left": {
        "samples": 17,
        "value": [
          3,
          14
        ],
        "predicted_class": "sedan",
        "impurity": 0.672,
        "feature": "penggerak",
        "feature_display": "penggerak (0=depan, 1=belakang)",
        "threshold": 0.5,
        "left": {
          "samples": 16,
          "value": [
            2,
            14
          ],
          "predicted_class": "sedan",
          "impurity": 0.544,
          "feature": "bangku",
          "feature_display": "bangku",
          "threshold": 3.0,
          "left": {
            "samples": 4,
            "value": [
              0,
              4
            ],
            "predicted_class": "sedan",
            "impurity": 0.0
          },
          "right": {
            "samples": 12,
            "value": [
              2,
              10
            ],
            "predicted_class": "sedan",
            "impurity": 0.65
          }
        },
        "right": {
          "samples": 1,
          "value": [
            1,
            0
          ],
          "predicted_class": "minibus",
          "impurity": 0.0
        }
      },
      "right": {
        "samples": 15,
        "value": [
          15,
          0
        ],
        "predicted_class": "minibus",
        "impurity": 0.0
      }
    },
    "class_names": [
      "minibus",
      "sedan"
    ]
  }
};
