// Auto-generated by generate_nb_data.py
// Naive Bayes data for KupasAI ML Week 7 - toy spam example (Modul 7.2) + real Titanic dataset

const NB_DATA = {
  "bayes_toy": {
    "emails": [
      {
        "diskon": true,
        "hadiah": false,
        "kelas": "Spam"
      },
      {
        "diskon": false,
        "hadiah": true,
        "kelas": "Non-Spam"
      },
      {
        "diskon": true,
        "hadiah": true,
        "kelas": "Spam"
      },
      {
        "diskon": false,
        "hadiah": false,
        "kelas": "Non-Spam"
      }
    ],
    "prior": {
      "Spam": 0.5,
      "Non-Spam": 0.5
    }
  },
  "titanic": {
    "n_test": 179,
    "n_train": 712,
    "seed": 42,
    "label_source": "Survived from labeled train.csv, stratified 80/20 holdout",
    "imputation_train_only": {
      "Age": 28.5,
      "Fare": 14.4542,
      "Embarked": "S"
    },
    "f1": 0.7111,
    "confusion_matrix": [
      [
        92,
        18
      ],
      [
        21,
        48
      ]
    ],
    "accuracy": 0.7821
  }
};
