#!/usr/bin/env python3
"""
KupasAI - Naive Bayes Data Generator
Uses the exact 4-email toy dataset from Modul 7.2 for the Bayes calculator,
and the real Titanic dataset for the case study tab.
"""

import json
import os

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, f1_score

HERE = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.environ.get(
    "DASAR_ML_DIR",
    "https://raw.githubusercontent.com/FeliksMakarios/dasar-machine-learning/41db3dc8c328eab6e7fa5f5604194ab5e49c4d05",
)


def dataset_path(*parts):
    return "/".join([DATASET_DIR.rstrip("/")] + list(parts))


# ============================================================
# PART 1: spam/non-spam toy example (Modul 7.2), exact 4 rows
# ============================================================

emails = [
    {"diskon": True, "hadiah": False, "kelas": "Spam"},
    {"diskon": False, "hadiah": True, "kelas": "Non-Spam"},
    {"diskon": True, "hadiah": True, "kelas": "Spam"},
    {"diskon": False, "hadiah": False, "kelas": "Non-Spam"},
]

n = len(emails)
classes = ["Spam", "Non-Spam"]
prior = {c: sum(1 for e in emails if e["kelas"] == c) / n for c in classes}


def likelihood(feature, value, cls, alpha):
    subset = [e for e in emails if e["kelas"] == cls]
    n_cls = len(subset)
    n_match = sum(1 for e in subset if e[feature] == value)
    n_values = 2  # binary feature
    return (n_match + alpha) / (n_cls + n_values * alpha)


def posterior_table(diskon_val, hadiah_val, alpha):
    out = {}
    for c in classes:
        p_diskon = likelihood("diskon", diskon_val, c, alpha)
        p_hadiah = likelihood("hadiah", hadiah_val, c, alpha)
        out[c] = {
            "prior": round(prior[c], 4),
            "p_diskon": round(p_diskon, 4),
            "p_hadiah": round(p_hadiah, 4),
            "posterior_unnorm": round(prior[c] * p_diskon * p_hadiah, 6),
        }
    total = sum(v["posterior_unnorm"] for v in out.values())
    for c in classes:
        out[c]["posterior_norm"] = round(out[c]["posterior_unnorm"] / total, 4) if total > 0 else 0
    return out

bayes_toy = {
    "emails": emails,
    "prior": {c: round(prior[c], 4) for c in classes},
}

# ============================================================
# PART 2: Titanic dataset (real, GaussianNB)
# ============================================================

df = pd.read_csv(dataset_path("buku1", "titanic", "train.csv"))
df_train, df_joined = train_test_split(df, test_size=0.2, random_state=42, stratify=df["Survived"])
df_train = df_train.reset_index(drop=True)
df_joined = df_joined.reset_index(drop=True)
imputation = {"Age": float(df_train["Age"].median()), "Fare": float(df_train["Fare"].median()), "Embarked": df_train["Embarked"].mode()[0]}

def preprocess(d):
    d = d.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1)
    d["Age"] = d["Age"].fillna(imputation["Age"])
    d["Fare"] = d["Fare"].fillna(imputation["Fare"])
    d["Embarked"] = d["Embarked"].fillna(imputation["Embarked"])
    d["Sex"] = d["Sex"].map({"male": 0, "female": 1})
    d["Embarked"] = d["Embarked"].map({"C": 0, "Q": 1, "S": 2})
    return d


train_new = preprocess(df_train.copy())
test_new = preprocess(df_joined.copy())

X_train = train_new.drop("Survived", axis=1)
y_train = train_new["Survived"]
X_test = test_new.drop("Survived", axis=1)
y_test = test_new["Survived"]

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)
acc = accuracy_score(y_test, y_pred)

# Publish aggregate evaluation without passenger-level records.
data = {
    "bayes_toy": bayes_toy,
    "titanic": {
        "n_test": int(len(df_joined)),
        "n_train": len(df_train),
        "seed": 42,
        "label_source": "Survived from labeled train.csv, stratified 80/20 holdout",
        "imputation_train_only": imputation,
        "f1": round(float(f1_score(y_test, y_pred)), 4),
        "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
        "accuracy": round(float(acc), 4),
    },
}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_nb_data.py\n"
js += "// Naive Bayes data for KupasAI ML Week 7 - toy spam example (Modul 7.2) + real Titanic dataset\n\n"
js += "const NB_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("Prior:", prior)
print("Without smoothing (Diskon=Ya, Hadiah=Ya):", posterior_table(True, True, 0))
print("With smoothing (Diskon=Ya, Hadiah=Ya):", posterior_table(True, True, 1))
print("Titanic accuracy:", acc)
print("Written:", outpath)
