#!/usr/bin/env python3
"""
KupasAI - Naive Bayes Data Generator
Uses the exact 4-email toy dataset from Modul 7.2 for the Bayes calculator,
and the real Titanic dataset for the case study tab.
"""

import json
import os

import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

HERE = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.environ.get(
    "DASAR_ML_DIR",
    "https://raw.githubusercontent.com/FeliksMakarios/dasar-machine-learning/main",
)


def dataset_path(*parts):
    return "/".join([DATASET_DIR.rstrip("/")] + list(parts))


# ============================================================
# PART 1: spam/non-spam toy example (Modul 7.2), exact 4 rows
# ============================================================

emails = [
    {"diskon": True, "hadiah": False, "kelas": "Spam"},
    {"diskon": False, "hadiah": True, "kelas": "Non-Spam"},
    {"diskon": True, "hadiah": True, "kelas": "Spam"},
    {"diskon": False, "hadiah": False, "kelas": "Non-Spam"},
]

n = len(emails)
classes = ["Spam", "Non-Spam"]
prior = {c: sum(1 for e in emails if e["kelas"] == c) / n for c in classes}


def likelihood(feature, value, cls, alpha):
    subset = [e for e in emails if e["kelas"] == cls]
    n_cls = len(subset)
    n_match = sum(1 for e in subset if e[feature] == value)
    n_values = 2  # binary feature
    return (n_match + alpha) / (n_cls + n_values * alpha)


def posterior_table(diskon_val, hadiah_val, alpha):
    out = {}
    for c in classes:
        p_diskon = likelihood("diskon", diskon_val, c, alpha)
        p_hadiah = likelihood("hadiah", hadiah_val, c, alpha)
        out[c] = {
            "prior": round(prior[c], 4),
            "p_diskon": round(p_diskon, 4),
            "p_hadiah": round(p_hadiah, 4),
            "posterior_unnorm": round(prior[c] * p_diskon * p_hadiah, 6),
        }
    total = sum(v["posterior_unnorm"] for v in out.values())
    for c in classes:
        out[c]["posterior_norm"] = round(out[c]["posterior_unnorm"] / total, 4) if total > 0 else 0
    return out

bayes_toy = {
    "emails": emails,
    "prior": {c: round(prior[c], 4) for c in classes},
}

# ============================================================
# PART 2: Titanic dataset (real, GaussianNB)
# ============================================================

df_train = pd.read_csv(dataset_path("buku1", "titanic", "train.csv"))
df_test = pd.read_csv(dataset_path("buku1", "titanic", "test.csv"))
df_gender = pd.read_csv(dataset_path("buku1", "titanic", "gender_submission.csv"))
df_joined = pd.merge(df_test, df_gender, on="PassengerId")


def preprocess(d):
    d = d.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1)
    d["Age"] = d["Age"].fillna(d["Age"].median())
    d["Fare"] = d["Fare"].fillna(d["Fare"].median())
    d["Embarked"] = d["Embarked"].fillna(d["Embarked"].mode()[0])
    d["Sex"] = d["Sex"].map({"male": 0, "female": 1})
    d["Embarked"] = d["Embarked"].map({"C": 0, "Q": 1, "S": 2})
    return d


train_new = preprocess(df_train.copy())
test_new = preprocess(df_joined.copy())

X_train = train_new.drop("Survived", axis=1)
y_train = train_new["Survived"]
X_test = test_new.drop("Survived", axis=1)
y_test = test_new["Survived"]

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)
acc = accuracy_score(y_test, y_pred)

# Sample passengers for the interactive picker (first 12 of test set)
passengers_raw = df_joined.head(12)
sample_idx = passengers_raw.index
titanic_samples = []
for i in sample_idx:
    row = df_joined.loc[i]
    titanic_samples.append({
        "name": row["Name"],
        "pclass": int(row["Pclass"]),
        "sex": row["Sex"],
        "age": None if pd.isna(row["Age"]) else float(row["Age"]),
        "fare": round(float(row["Fare"]), 2) if not pd.isna(row["Fare"]) else None,
        "embarked": row["Embarked"],
        "actual": int(row["Survived"]),
        "predicted": int(y_pred[list(df_joined.index).index(i)]),
        "proba_survive": round(float(y_proba[list(df_joined.index).index(i)][1]), 4),
    })

data = {
    "bayes_toy": bayes_toy,
    "titanic": {
        "n_test": int(len(df_joined)),
        "accuracy": round(float(acc), 4),
        "samples": titanic_samples,
    },
}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_nb_data.py\n"
js += "// Naive Bayes data for KupasAI ML Week 7 - toy spam example (Modul 7.2) + real Titanic dataset\n\n"
js += "const NB_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("Prior:", prior)
print("Without smoothing (Diskon=Ya, Hadiah=Ya):", posterior_table(True, True, 0))
print("With smoothing (Diskon=Ya, Hadiah=Ya):", posterior_table(True, True, 1))
print("Titanic accuracy:", acc)
print("Written:", outpath)
