// Generated by scripts/generate_advanced.py. Seed 42 unless specified.
var BP_DATA = {
  "x": [
    1.0,
    0.5,
    -2.0
  ],
  "target": 0.8,
  "alpha": 0.1,
  "W01_initial": [
    [
      0.2,
      -0.1,
      0.4,
      0.0
    ],
    [
      -0.3,
      0.5,
      -0.2,
      1.0
    ],
    [
      0.1,
      0.2,
      0.0,
      -0.5
    ]
  ],
  "W12_initial": [
    0.0,
    0.5,
    1.0,
    -1.0
  ],
  "W01_final": [
    [
      0.2,
      -0.1,
      0.6,
      -0.2
    ],
    [
      -0.3,
      0.5,
      -0.1,
      0.9
    ],
    [
      0.1,
      0.2,
      -0.4,
      -0.1
    ]
  ],
  "W12_final": [
    0.0,
    0.5,
    1.06,
    -0.7
  ],
  "steps": [
    {
      "title": "0. Nilai awal",
      "phase": "setup",
      "hidden": [
        null,
        null,
        null,
        null
      ],
      "output": null,
      "hiddenSub": "",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "Objektif L = ½(ŷ − t)². MSE = (ŷ − t)²."
      ]
    },
    {
      "title": "1. Pra-aktivasi",
      "phase": "forward",
      "hidden": [
        -0.15,
        -0.25,
        0.3,
        1.5
      ],
      "output": null,
      "hiddenSub": "z₁",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "z = xW = [-0.15, -0.25, 0.3, 1.5]"
      ]
    },
    {
      "title": "2. Aktivasi ReLU",
      "phase": "forward",
      "hidden": [
        0.0,
        0.0,
        0.3,
        1.5
      ],
      "output": null,
      "hiddenSub": "h",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "h = max(0,z) = [0.0, 0.0, 0.3, 1.5]"
      ]
    },
    {
      "title": "3. Keluaran",
      "phase": "forward",
      "hidden": [
        0.0,
        0.0,
        0.3,
        1.5
      ],
      "output": -1.2,
      "hiddenSub": "h",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "ŷ = hW = -1.2000"
      ]
    },
    {
      "title": "4. Galat",
      "phase": "compare",
      "hidden": [
        0.0,
        0.0,
        0.3,
        1.5
      ],
      "output": -1.2,
      "hiddenSub": "h",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "delta = ŷ − t = -2.0000",
        "L = 2.0000, MSE = 4.0000"
      ]
    },
    {
      "title": "5. Gradien bobot keluaran",
      "phase": "backward",
      "hidden": [
        0.0,
        0.0,
        0.3,
        1.5
      ],
      "output": -1.2,
      "hiddenSub": "h",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "∂L/∂W₁₂ = h × delta = [-0.0, -0.0, -0.6, -3.0]",
        "Bobot belum diperbarui."
      ]
    },
    {
      "title": "6. Gradien tersembunyi",
      "phase": "backward",
      "hidden": [
        -0.0,
        -0.0,
        -2.0,
        2.0
      ],
      "output": -1.2,
      "hiddenSub": "delta_h",
      "W01": [
        [
          0.2,
          -0.1,
          0.4,
          0.0
        ],
        [
          -0.3,
          0.5,
          -0.2,
          1.0
        ],
        [
          0.1,
          0.2,
          0.0,
          -0.5
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.0,
        -1.0
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "delta_h = delta × W₁₂ lama × ReLU′(z) = [-0.0, -0.0, -2.0, 2.0]"
      ]
    },
    {
      "title": "7. Gradien masukan dan pembaruan serentak",
      "phase": "backward",
      "hidden": [
        -0.0,
        -0.0,
        -2.0,
        2.0
      ],
      "output": -1.2,
      "hiddenSub": "delta_h",
      "W01": [
        [
          0.2,
          -0.1,
          0.6,
          -0.2
        ],
        [
          -0.3,
          0.5,
          -0.1,
          0.9
        ],
        [
          0.1,
          0.2,
          -0.4,
          -0.1
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.06,
        -0.7
      ],
      "W01highlight": true,
      "W12highlight": true,
      "trace": [
        "∂L/∂W₀₁ = outer(x,delta_h) = [[-0.0, -0.0, -2.0, 2.0], [-0.0, -0.0, -1.0, 1.0], [0.0, 0.0, 4.0, -4.0]]",
        "W baru = W lama − 0,1 × gradien. Kedua matriks diperbarui setelah semua gradien tersedia."
      ]
    },
    {
      "title": "8. Verifikasi",
      "phase": "verify",
      "hidden": [
        0.0,
        0.0,
        1.35,
        0.45
      ],
      "output": 1.116,
      "hiddenSub": "h'",
      "W01": [
        [
          0.2,
          -0.1,
          0.6,
          -0.2
        ],
        [
          -0.3,
          0.5,
          -0.1,
          0.9
        ],
        [
          0.1,
          0.2,
          -0.4,
          -0.1
        ]
      ],
      "W12": [
        0.0,
        0.5,
        1.06,
        -0.7
      ],
      "W01highlight": false,
      "W12highlight": false,
      "trace": [
        "ŷ baru = 1.1160",
        "MSE baru = 0.099856"
      ]
    }
  ],
  "mseHistory": [
    4.0,
    0.099856
  ]
};
