// Generated by scripts/generate_advanced.py. Seed 42 unless specified.
var GD_DATA = {
  "compare": {
    "weight0": 0.5,
    "input": 0.5,
    "goal": 0.8,
    "lr": 0.01,
    "hot_cold": [
      {
        "iter": 1,
        "weight": 0.51,
        "error": 0.297025
      },
      {
        "iter": 2,
        "weight": 0.52,
        "error": 0.2916
      },
      {
        "iter": 3,
        "weight": 0.53,
        "error": 0.286225
      },
      {
        "iter": 4,
        "weight": 0.54,
        "error": 0.2809
      },
      {
        "iter": 5,
        "weight": 0.55,
        "error": 0.275625
      },
      {
        "iter": 6,
        "weight": 0.56,
        "error": 0.2704
      },
      {
        "iter": 7,
        "weight": 0.57,
        "error": 0.265225
      },
      {
        "iter": 8,
        "weight": 0.58,
        "error": 0.2601
      },
      {
        "iter": 9,
        "weight": 0.59,
        "error": 0.255025
      },
      {
        "iter": 10,
        "weight": 0.6,
        "error": 0.25
      }
    ],
    "gd": [
      {
        "iter": 1,
        "weight": 0.775,
        "error": 0.17015625
      },
      {
        "iter": 2,
        "weight": 0.98125,
        "error": 0.09571289
      },
      {
        "iter": 3,
        "weight": 1.1359375,
        "error": 0.0538385
      },
      {
        "iter": 4,
        "weight": 1.25195312,
        "error": 0.03028416
      },
      {
        "iter": 5,
        "weight": 1.33896484,
        "error": 0.01703484
      },
      {
        "iter": 6,
        "weight": 1.40422363,
        "error": 0.0095821
      },
      {
        "iter": 7,
        "weight": 1.45316772,
        "error": 0.00538993
      },
      {
        "iter": 8,
        "weight": 1.48987579,
        "error": 0.00303184
      },
      {
        "iter": 9,
        "weight": 1.51740685,
        "error": 0.00170541
      },
      {
        "iter": 10,
        "weight": 1.53805513,
        "error": 0.00095929
      }
    ]
  },
  "oneIteration": {
    "weight": 0.1,
    "input": 8.5,
    "goal": 1.0,
    "alpha": 0.01,
    "steps": [
      {
        "name": "1. Prediksi",
        "formula": "pred = x × w",
        "value": "0.85"
      },
      {
        "name": "2. Delta",
        "formula": "delta = pred − target",
        "value": "-0.15"
      },
      {
        "name": "3. Gradien",
        "formula": "grad = x × delta",
        "value": "-1.275"
      },
      {
        "name": "4. Bobot baru",
        "formula": "w baru = w − alpha × grad",
        "value": "0.11275"
      },
      {
        "name": "5. Prediksi baru",
        "formula": "pred baru = x × w baru",
        "value": "0.958375"
      }
    ],
    "errorBefore": 0.0225,
    "errorAfter": 0.00173264
  },
  "alphaPresets": [
    {
      "label": "Normal",
      "input": 0.5,
      "alpha": 1
    },
    {
      "label": "Divergen",
      "input": 2,
      "alpha": 1
    },
    {
      "label": "Stabil",
      "input": 2,
      "alpha": 0.1
    }
  ]
};
