#!/usr/bin/env python3
"""
KupasAI - Logistic Regression Data Generator
Uses the real Iris dataset (Scikit-learn built-in) exactly as in Modul 4:
first 100 samples (Setosa vs Versicolor), first two features.
"""

import json
import os

import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

HERE = os.path.dirname(os.path.abspath(__file__))

iris = datasets.load_iris()
X = iris["data"][:100, :2]
y = iris["target"][:100]
feature_names = iris["feature_names"][:2]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

w = model.coef_[0]
b = model.intercept_[0]

# Decision boundary meshgrid (coarse grid of real predict_proba values)
x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
GRID_N = 40
xx = np.linspace(x_min, x_max, GRID_N)
yy = np.linspace(y_min, y_max, GRID_N)
grid_points = np.array([[a, c] for c in yy for a in xx])
proba_grid = model.predict_proba(grid_points)[:, 1].reshape(GRID_N, GRID_N)

data = {
    "feature_names": [str(f) for f in feature_names],
    "points": [
        {"x": float(X[i, 0]), "y": float(X[i, 1]), "label": int(y[i]), "test": bool(any(np.array_equal(X[i], xt) for xt in X_test))}
        for i in range(len(X))
    ],
    "w": [round(float(v), 4) for v in w],
    "b": round(float(b), 4),
    "x_range": [x_min, x_max],
    "y_range": [y_min, y_max],
    "grid_n": GRID_N,
    "proba_grid": [[round(float(v), 4) for v in row] for row in proba_grid],
    "accuracy": round(float(acc), 4),
    "confusion_matrix": cm.tolist(),
    "class_names": ["setosa", "versicolor"],
}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_logreg_data.py\n"
js += "// Logistic Regression data for KupasAI ML Week 4 - real Iris dataset (setosa vs versicolor)\n\n"
js += "const LOGREG_DATA = " + json.dumps(data) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("w:", w, "b:", b)
print("accuracy:", acc)
print("confusion matrix:", cm.tolist())
print("Written:", outpath)
