// Auto-generated by generate_mba_data.py
// Market Basket Analysis data for KupasAI ML Week 11 - real coffee shop transaction dataset

const MBA_DATA = {
  "n_trx": 8144,
  "n_products": 40,
  "min_support": 0.1,
  "min_confidence": 0.5,
  "min_pair_support": 0.01,
  "frequent_itemsets": [
    {
      "items": [
        "Teh Tubruk"
      ],
      "support": 0.3428
    },
    {
      "items": [
        "Mineral Water"
      ],
      "support": 0.2247
    },
    {
      "items": [
        "Pisang Goreng"
      ],
      "support": 0.2067
    },
    {
      "items": [
        "Nasi Putih"
      ],
      "support": 0.1968
    },
    {
      "items": [
        "Kopi Tubruk"
      ],
      "support": 0.1776
    },
    {
      "items": [
        "Soto Ayam"
      ],
      "support": 0.1735
    },
    {
      "items": [
        "Nasi Goreng Jawa"
      ],
      "support": 0.1703
    },
    {
      "items": [
        "Rawon"
      ],
      "support": 0.1541
    },
    {
      "items": [
        "Bakmi Godog Keju"
      ],
      "support": 0.1315
    },
    {
      "items": [
        "Extra Kerupuk Putih"
      ],
      "support": 0.1299
    },
    {
      "items": [
        "Pisang Goreng",
        "Teh Tubruk"
      ],
      "support": 0.1227
    },
    {
      "items": [
        "Fresh Orange Juice"
      ],
      "support": 0.1116
    },
    {
      "items": [
        "Bakmi Goreng Jawa"
      ],
      "support": 0.1114
    },
    {
      "items": [
        "Latte"
      ],
      "support": 0.1093
    },
    {
      "items": [
        "Mineral Water",
        "Nasi Goreng Jawa"
      ],
      "support": 0.104
    },
    {
      "items": [
        "Mineral Water",
        "Teh Tubruk"
      ],
      "support": 0.1018
    }
  ],
  "rules": [
    {
      "antecedents": [
        "Nasi Goreng Jawa"
      ],
      "consequents": [
        "Mineral Water"
      ],
      "support": 0.104,
      "confidence": 0.6107,
      "lift": 2.7177,
      "leverage": 0.0657,
      "conviction": 1.9914
    },
    {
      "antecedents": [
        "Pisang Goreng"
      ],
      "consequents": [
        "Teh Tubruk"
      ],
      "support": 0.1227,
      "confidence": 0.5936,
      "lift": 1.7314,
      "leverage": 0.0518,
      "conviction": 1.617
    }
  ],
  "products": [
    "Americano",
    "Bakmi Godog Keju",
    "Bakmi Goreng Jawa",
    "Bakwan Goreng",
    "Cappuccino",
    "Double Espresso",
    "Es Batu",
    "Es Teh Susu (Gula Jawa)",
    "Espresso",
    "Extra Kerupuk Putih",
    "French Fries",
    "Fresh Orange Juice",
    "Green Tea",
    "Hot Chocolate",
    "Hot/Ice Lemon Tea",
    "Iced Peach Tea",
    "Iced Tea",
    "Indomie Goreng (J)",
    "Indomie Goreng (R)",
    "Indomie Goreng Aceh",
    "Jasmine",
    "Kopi Tubruk",
    "Latte",
    "Lemon Tea",
    "Macchiato",
    "Macchiato ",
    "Milo Dinosaur",
    "Mineral Water",
    "Nasi Goreng Jawa",
    "Nasi Putih",
    "Pisang Goreng",
    "Pisang Goreng Tuna Sandwich",
    "Rawon",
    "Roti Bakar",
    "Soto Ayam",
    "Spaghetti Bolognese",
    "Takjil",
    "Teh Tarik",
    "Teh Tubruk",
    "Telur Orak Arik"
  ],
  "support_single": {
    "Americano": 0.055,
    "Bakmi Godog Keju": 0.1315,
    "Bakmi Goreng Jawa": 0.1114,
    "Bakwan Goreng": 0.0039,
    "Cappuccino": 0.0882,
    "Double Espresso": 0.0026,
    "Es Batu": 0.0006,
    "Es Teh Susu (Gula Jawa)": 0.0006,
    "Espresso": 0.0126,
    "Extra Kerupuk Putih": 0.1299,
    "French Fries": 0.0522,
    "Fresh Orange Juice": 0.1116,
    "Green Tea": 0.0012,
    "Hot Chocolate": 0.0021,
    "Hot/Ice Lemon Tea": 0.0594,
    "Iced Peach Tea": 0.0005,
    "Iced Tea": 0.0077,
    "Indomie Goreng (J)": 0.0016,
    "Indomie Goreng (R)": 0.0018,
    "Indomie Goreng Aceh": 0.0005,
    "Jasmine": 0.0004,
    "Kopi Tubruk": 0.1776,
    "Latte": 0.1093,
    "Lemon Tea": 0.0006,
    "Macchiato": 0.0645,
    "Macchiato ": 0.0106,
    "Milo Dinosaur": 0.0048,
    "Mineral Water": 0.2247,
    "Nasi Goreng Jawa": 0.1703,
    "Nasi Putih": 0.1968,
    "Pisang Goreng": 0.2067,
    "Pisang Goreng Tuna Sandwich": 0.0002,
    "Rawon": 0.1541,
    "Roti Bakar": 0.0936,
    "Soto Ayam": 0.1735,
    "Spaghetti Bolognese": 0.0328,
    "Takjil": 0.0001,
    "Teh Tarik": 0.0992,
    "Teh Tubruk": 0.3428,
    "Telur Orak Arik": 0.001
  },
  "pair_stats": {
    "Americano": [
      {
        "with": "Pisang Goreng",
        "support": 0.0146,
        "confidence": 0.2656,
        "lift": 1.2854
      },
      {
        "with": "Mineral Water",
        "support": 0.015,
        "confidence": 0.2723,
        "lift": 1.2119
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0169,
        "confidence": 0.308,
        "lift": 0.8985
      }
    ],
    "Bakmi Godog Keju": [
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0167,
        "confidence": 0.127,
        "lift": 2.1367
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0952,
        "confidence": 0.7236,
        "lift": 2.1107
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0293,
        "confidence": 0.2232,
        "lift": 1.7178
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.023,
        "confidence": 0.1746,
        "lift": 1.5643
      },
      {
        "with": "Mineral Water",
        "support": 0.0444,
        "confidence": 0.338,
        "lift": 1.5042
      }
    ],
    "Bakmi Goreng Jawa": [
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0134,
        "confidence": 0.1202,
        "lift": 2.0221
      },
      {
        "with": "Nasi Goreng Jawa",
        "support": 0.0327,
        "confidence": 0.2933,
        "lift": 1.722
      },
      {
        "with": "Mineral Water",
        "support": 0.0409,
        "confidence": 0.3671,
        "lift": 1.6339
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.0203,
        "confidence": 0.1819,
        "lift": 1.6299
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0596,
        "confidence": 0.5347,
        "lift": 1.5598
      }
    ],
    "Bakwan Goreng": [],
    "Cappuccino": [
      {
        "with": "Roti Bakar",
        "support": 0.0128,
        "confidence": 0.1448,
        "lift": 1.5481
      },
      {
        "with": "Latte",
        "support": 0.012,
        "confidence": 0.1365,
        "lift": 1.249
      },
      {
        "with": "Pisang Goreng",
        "support": 0.0211,
        "confidence": 0.2396,
        "lift": 1.1592
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0243,
        "confidence": 0.2758,
        "lift": 0.8044
      },
      {
        "with": "Mineral Water",
        "support": 0.0151,
        "confidence": 0.1713,
        "lift": 0.7624
      }
    ],
    "Double Espresso": [],
    "Es Batu": [],
    "Es Teh Susu (Gula Jawa)": [],
    "Espresso": [],
    "Extra Kerupuk Putih": [
      {
        "with": "Nasi Goreng Jawa",
        "support": 0.0718,
        "confidence": 0.5529,
        "lift": 3.2466
      },
      {
        "with": "Mineral Water",
        "support": 0.0523,
        "confidence": 0.4026,
        "lift": 1.7919
      },
      {
        "with": "Kopi Tubruk",
        "support": 0.0409,
        "confidence": 0.3147,
        "lift": 1.7727
      },
      {
        "with": "Bakmi Godog Keju",
        "support": 0.0293,
        "confidence": 0.2259,
        "lift": 1.7178
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0131,
        "confidence": 0.1011,
        "lift": 1.7017
      }
    ],
    "French Fries": [
      {
        "with": "Mineral Water",
        "support": 0.0138,
        "confidence": 0.2635,
        "lift": 1.1728
      },
      {
        "with": "Kopi Tubruk",
        "support": 0.0103,
        "confidence": 0.1976,
        "lift": 1.1132
      },
      {
        "with": "Pisang Goreng",
        "support": 0.0115,
        "confidence": 0.2212,
        "lift": 1.0703
      },
      {
        "with": "Teh Tubruk",
        "support": 0.019,
        "confidence": 0.3647,
        "lift": 1.0638
      }
    ],
    "Fresh Orange Juice": [
      {
        "with": "Spaghetti Bolognese",
        "support": 0.0328,
        "confidence": 0.2937,
        "lift": 8.9593
      },
      {
        "with": "Bakmi Goreng Jawa",
        "support": 0.0203,
        "confidence": 0.1815,
        "lift": 1.6299
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0228,
        "confidence": 0.2046,
        "lift": 1.5751
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0104,
        "confidence": 0.0935,
        "lift": 1.5734
      },
      {
        "with": "Bakmi Godog Keju",
        "support": 0.023,
        "confidence": 0.2057,
        "lift": 1.5643
      }
    ],
    "Green Tea": [],
    "Hot Chocolate": [],
    "Hot/Ice Lemon Tea": [
      {
        "with": "Bakmi Godog Keju",
        "support": 0.0167,
        "confidence": 0.281,
        "lift": 2.1367
      },
      {
        "with": "Bakmi Goreng Jawa",
        "support": 0.0134,
        "confidence": 0.2252,
        "lift": 2.0221
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0131,
        "confidence": 0.2211,
        "lift": 1.7017
      },
      {
        "with": "Nasi Goreng Jawa",
        "support": 0.0168,
        "confidence": 0.2831,
        "lift": 1.662
      },
      {
        "with": "Mineral Water",
        "support": 0.0212,
        "confidence": 0.3574,
        "lift": 1.5907
      }
    ],
    "Iced Peach Tea": [],
    "Iced Tea": [],
    "Indomie Goreng (J)": [],
    "Indomie Goreng (R)": [],
    "Indomie Goreng Aceh": [],
    "Jasmine": [],
    "Kopi Tubruk": [
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0409,
        "confidence": 0.2303,
        "lift": 1.7727
      },
      {
        "with": "Nasi Goreng Jawa",
        "support": 0.0448,
        "confidence": 0.2524,
        "lift": 1.4821
      },
      {
        "with": "Roti Bakar",
        "support": 0.0187,
        "confidence": 0.1051,
        "lift": 1.1235
      },
      {
        "with": "French Fries",
        "support": 0.0103,
        "confidence": 0.0581,
        "lift": 1.1132
      },
      {
        "with": "Teh Tarik",
        "support": 0.0183,
        "confidence": 0.103,
        "lift": 1.0386
      }
    ],
    "Latte": [
      {
        "with": "Roti Bakar",
        "support": 0.0151,
        "confidence": 0.1382,
        "lift": 1.4771
      },
      {
        "with": "Cappuccino",
        "support": 0.012,
        "confidence": 0.1101,
        "lift": 1.249
      },
      {
        "with": "Pisang Goreng",
        "support": 0.0264,
        "confidence": 0.2416,
        "lift": 1.169
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.0139,
        "confidence": 0.127,
        "lift": 1.1375
      },
      {
        "with": "Teh Tarik",
        "support": 0.0104,
        "confidence": 0.0955,
        "lift": 0.9626
      }
    ],
    "Lemon Tea": [],
    "Macchiato": [
      {
        "with": "Rawon",
        "support": 0.0108,
        "confidence": 0.1676,
        "lift": 1.0877
      },
      {
        "with": "Pisang Goreng",
        "support": 0.0131,
        "confidence": 0.2038,
        "lift": 0.9862
      },
      {
        "with": "Mineral Water",
        "support": 0.0134,
        "confidence": 0.2076,
        "lift": 0.924
      },
      {
        "with": "Soto Ayam",
        "support": 0.0102,
        "confidence": 0.1581,
        "lift": 0.9112
      },
      {
        "with": "Nasi Putih",
        "support": 0.0109,
        "confidence": 0.1695,
        "lift": 0.8613
      }
    ],
    "Macchiato ": [],
    "Milo Dinosaur": [],
    "Mineral Water": [
      {
        "with": "Nasi Goreng Jawa",
        "support": 0.104,
        "confidence": 0.4628,
        "lift": 2.7177
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0523,
        "confidence": 0.2328,
        "lift": 1.7919
      },
      {
        "with": "Bakmi Goreng Jawa",
        "support": 0.0409,
        "confidence": 0.182,
        "lift": 1.6339
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0212,
        "confidence": 0.0945,
        "lift": 1.5907
      },
      {
        "with": "Bakmi Godog Keju",
        "support": 0.0444,
        "confidence": 0.1978,
        "lift": 1.5042
      }
    ],
    "Nasi Goreng Jawa": [
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0718,
        "confidence": 0.4218,
        "lift": 3.2466
      },
      {
        "with": "Mineral Water",
        "support": 0.104,
        "confidence": 0.6107,
        "lift": 2.7177
      },
      {
        "with": "Bakmi Goreng Jawa",
        "support": 0.0327,
        "confidence": 0.1918,
        "lift": 1.722
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0168,
        "confidence": 0.0988,
        "lift": 1.662
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0869,
        "confidence": 0.5105,
        "lift": 1.4889
      }
    ],
    "Nasi Putih": [
      {
        "with": "Rawon",
        "support": 0.0861,
        "confidence": 0.4373,
        "lift": 2.8378
      },
      {
        "with": "Soto Ayam",
        "support": 0.0737,
        "confidence": 0.3743,
        "lift": 2.1573
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0162,
        "confidence": 0.0823,
        "lift": 1.3856
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.0302,
        "confidence": 0.1535,
        "lift": 1.3749
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0335,
        "confidence": 0.1703,
        "lift": 1.3109
      }
    ],
    "Pisang Goreng": [
      {
        "with": "Teh Tubruk",
        "support": 0.1227,
        "confidence": 0.5936,
        "lift": 1.7314
      },
      {
        "with": "Bakmi Godog Keju",
        "support": 0.0355,
        "confidence": 0.1717,
        "lift": 1.3058
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.03,
        "confidence": 0.145,
        "lift": 1.2989
      },
      {
        "with": "Americano",
        "support": 0.0146,
        "confidence": 0.0707,
        "lift": 1.2854
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0157,
        "confidence": 0.0761,
        "lift": 1.2797
      }
    ],
    "Pisang Goreng Tuna Sandwich": [],
    "Rawon": [
      {
        "with": "Nasi Putih",
        "support": 0.0861,
        "confidence": 0.5586,
        "lift": 2.8378
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.0235,
        "confidence": 0.1522,
        "lift": 1.3635
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0123,
        "confidence": 0.0797,
        "lift": 1.3408
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0227,
        "confidence": 0.1474,
        "lift": 1.1347
      },
      {
        "with": "Soto Ayam",
        "support": 0.0301,
        "confidence": 0.1952,
        "lift": 1.1252
      }
    ],
    "Roti Bakar": [
      {
        "with": "Cappuccino",
        "support": 0.0128,
        "confidence": 0.1365,
        "lift": 1.5481
      },
      {
        "with": "Latte",
        "support": 0.0151,
        "confidence": 0.1614,
        "lift": 1.4771
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0178,
        "confidence": 0.1903,
        "lift": 1.4648
      },
      {
        "with": "Teh Tarik",
        "support": 0.0122,
        "confidence": 0.1299,
        "lift": 1.3095
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.0135,
        "confidence": 0.1444,
        "lift": 1.2933
      }
    ],
    "Soto Ayam": [
      {
        "with": "Nasi Putih",
        "support": 0.0737,
        "confidence": 0.4246,
        "lift": 2.1573
      },
      {
        "with": "Extra Kerupuk Putih",
        "support": 0.0352,
        "confidence": 0.2031,
        "lift": 1.5635
      },
      {
        "with": "Hot/Ice Lemon Tea",
        "support": 0.0153,
        "confidence": 0.0885,
        "lift": 1.4885
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0855,
        "confidence": 0.4926,
        "lift": 1.4368
      },
      {
        "with": "Fresh Orange Juice",
        "support": 0.0273,
        "confidence": 0.1571,
        "lift": 1.4076
      }
    ],
    "Spaghetti Bolognese": [
      {
        "with": "Fresh Orange Juice",
        "support": 0.0328,
        "confidence": 1.0,
        "lift": 8.9593
      },
      {
        "with": "Mineral Water",
        "support": 0.0101,
        "confidence": 0.3071,
        "lift": 1.3668
      },
      {
        "with": "Teh Tubruk",
        "support": 0.0138,
        "confidence": 0.4195,
        "lift": 1.2236
      }
    ],
    "Takjil": [],
    "Teh Tarik": [
      {
        "with": "Fresh Orange Juice",
        "support": 0.0156,
        "confidence": 0.1572,
        "lift": 1.4082
      },
      {
        "with": "Roti Bakar",
        "support": 0.0122,
        "confidence": 0.1225,
        "lift": 1.3095
      },
      {
        "with": "Pisang Goreng",
        "support": 0.0258,
        "confidence": 0.2599,
        "lift": 1.2577
      },
      {
        "with": "Bakmi Goreng Jawa",
        "support": 0.0136,
        "confidence": 0.1374,
        "lift": 1.2335
      },
      {
        "with": "Bakmi Godog Keju",
        "support": 0.0139,
        "confidence": 0.1399,
        "lift": 1.0634
      }
    ],
    "Teh Tubruk": [
      {
        "with": "Bakmi Godog Keju",
        "support": 0.0952,
        "confidence": 0.2776,
        "lift": 2.1107
      },
      {
        "with": "Pisang Goreng",
        "support": 0.1227,
        "confidence": 0.3578,
        "lift": 1.7314
      },
      {
        "with": "Bakmi Goreng Jawa",
        "support": 0.0596,
        "confidence": 0.1737,
        "lift": 1.5598
      },
      {
        "with": "Nasi Goreng Jawa",
        "support": 0.0869,
        "confidence": 0.2536,
        "lift": 1.4889
      },
      {
        "with": "Soto Ayam",
        "support": 0.0855,
        "confidence": 0.2493,
        "lift": 1.4368
      }
    ],
    "Telur Orak Arik": []
  }
};
