#!/usr/bin/env python3
"""
KupasAI - Market Basket Analysis Data Generator
Real coffee shop transaction dataset (Modul 11), Apriori + association rules (mlxtend).
"""

import json
import os
from itertools import combinations

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

HERE = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.environ.get(
    "DASAR_ML_DIR",
    "https://raw.githubusercontent.com/FeliksMakarios/dasar-machine-learning/main",
)


def dataset_path(*parts):
    return "/".join([DATASET_DIR.rstrip("/")] + list(parts))


data = pd.read_csv(dataset_path("buku1", "ch11", "semua_transaksi_ch11b.csv"))

transactions = data.groupby("TRX_ID")["PRODUCT_NAME"].apply(list).tolist()
n_trx = len(transactions)

te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

# ---- Apriori: same thresholds as the notebook ----
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

itemsets_out = []
for _, row in frequent_itemsets.iterrows():
    items = sorted(list(row["itemsets"]))
    itemsets_out.append({"items": items, "support": round(float(row["support"]), 4)})
itemsets_out.sort(key=lambda x: -x["support"])

rules_out = []
for _, row in rules.iterrows():
    rules_out.append({
        "antecedents": sorted(list(row["antecedents"])),
        "consequents": sorted(list(row["consequents"])),
        "support": round(float(row["support"]), 4),
        "confidence": round(float(row["confidence"]), 4),
        "lift": round(float(row["lift"]), 4),
        "leverage": round(float(row["leverage"]), 4),
        "conviction": round(float(row["conviction"]), 4),
    })

# ---- Full pairwise exploration (all products, lower threshold) ----
all_products = sorted(df.columns.tolist())
support_single = {p: float(df[p].mean()) for p in all_products}

MIN_PAIR_SUPPORT = 0.01  # filter out noisy pairs from very few co-occurrences

pair_stats = {p: [] for p in all_products}
for a, b in combinations(all_products, 2):
    both = float((df[a] & df[b]).mean())
    if both < MIN_PAIR_SUPPORT:
        continue
    conf_ab = both / support_single[a]
    conf_ba = both / support_single[b]
    lift = both / (support_single[a] * support_single[b])
    pair_stats[a].append({"with": b, "support": round(both, 4), "confidence": round(conf_ab, 4), "lift": round(lift, 4)})
    pair_stats[b].append({"with": a, "support": round(both, 4), "confidence": round(conf_ba, 4), "lift": round(lift, 4)})

for p in all_products:
    pair_stats[p].sort(key=lambda x: -x["lift"])
    pair_stats[p] = pair_stats[p][:5]

data_out = {
    "n_trx": n_trx,
    "n_products": len(all_products),
    "min_support": 0.1,
    "min_confidence": 0.5,
    "min_pair_support": MIN_PAIR_SUPPORT,
    "frequent_itemsets": itemsets_out,
    "rules": rules_out,
    "products": all_products,
    "support_single": {p: round(v, 4) for p, v in support_single.items()},
    "pair_stats": pair_stats,
}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_mba_data.py\n"
js += "// Market Basket Analysis data for KupasAI ML Week 11 - real coffee shop transaction dataset\n\n"
js += "const MBA_DATA = " + json.dumps(data_out, indent=2, ensure_ascii=False) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("n_trx:", n_trx, "n_products:", len(all_products))
print("frequent_itemsets:", len(itemsets_out))
print("rules:", rules_out)
print("Written:", outpath)
