// Auto-generated by generate_rf_data.py
// Random Forest data for KupasAI ML Week 6 - decisiontree_ch6.csv + UCI Adult census

const RF_DATA = {
  "ensemble_demo": {
    "test_rows": [
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "actual": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "actual": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 8,
        "penggerak": "belakang",
        "actual": "sedan"
      },
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "actual": "minibus"
      },
      {
        "mesin": "diesel",
        "bangku": 8,
        "penggerak": "belakang",
        "actual": "minibus"
      },
      {
        "mesin": "bensin",
        "bangku": 4,
        "penggerak": "depan",
        "actual": "minibus"
      },
      {
        "mesin": "diesel",
        "bangku": 5,
        "penggerak": "belakang",
        "actual": "sedan"
      },
      {
        "mesin": "bensin",
        "bangku": 7,
        "penggerak": "belakang",
        "actual": "sedan"
      }
    ],
    "single_tree_pred": [
      "minibus",
      "minibus",
      "sedan",
      "minibus",
      "minibus",
      "minibus",
      "sedan",
      "sedan"
    ],
    "single_tree_acc": 1.0,
    "mini_trees": [
      {
        "features": [
          "penggerak",
          "bangku"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      },
      {
        "features": [
          "mesin",
          "bangku"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      },
      {
        "features": [
          "bangku",
          "mesin"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      },
      {
        "features": [
          "penggerak",
          "mesin"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      },
      {
        "features": [
          "bangku",
          "mesin"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      },
      {
        "features": [
          "mesin",
          "penggerak"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      },
      {
        "features": [
          "penggerak",
          "mesin"
        ],
        "preds": [
          "minibus",
          "minibus",
          "sedan",
          "minibus",
          "minibus",
          "minibus",
          "sedan",
          "sedan"
        ]
      }
    ],
    "rf_pred": [
      "minibus",
      "minibus",
      "sedan",
      "minibus",
      "minibus",
      "minibus",
      "sedan",
      "sedan"
    ],
    "rf_acc": 1.0
  },
  "adult": {
    "n_rows": 32561,
    "accuracy": 0.8454,
    "report": {
      "<=50K": {
        "precision": 0.8831,
        "recall": 0.9166,
        "f1-score": 0.8995,
        "support": 4918.0
      },
      ">50K": {
        "precision": 0.7088,
        "recall": 0.6257,
        "f1-score": 0.6647,
        "support": 1595.0
      }
    },
    "feature_importance": [
      {
        "feature": "age",
        "importance": 0.2167
      },
      {
        "feature": "capital-gain",
        "importance": 0.1269
      },
      {
        "feature": "relationship_code",
        "importance": 0.1153
      },
      {
        "feature": "hrs-per-week",
        "importance": 0.1098
      },
      {
        "feature": "education-num",
        "importance": 0.0995
      },
      {
        "feature": "occupation_code",
        "importance": 0.088
      },
      {
        "feature": "marital-status_code",
        "importance": 0.0662
      },
      {
        "feature": "workclass_code",
        "importance": 0.0505
      },
      {
        "feature": "capital-loss",
        "importance": 0.0396
      },
      {
        "feature": "education_code",
        "importance": 0.0342
      },
      {
        "feature": "native_code",
        "importance": 0.0209
      },
      {
        "feature": "race_code",
        "importance": 0.0177
      },
      {
        "feature": "sex_code",
        "importance": 0.0147
      }
    ]
  }
};
