#!/usr/bin/env python3
"""
KupasAI - Random Forest Data Generator
Uses the real datasets from Modul 6: decisiontree_ch6.csv (ensemble voting
demo) and the UCI Adult census dataset (feature importance + metrics).
"""

import json
import os

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

HERE = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.environ.get(
    "DASAR_ML_DIR",
    "https://raw.githubusercontent.com/FeliksMakarios/dasar-machine-learning/main",
)


def dataset_path(*parts):
    return "/".join([DATASET_DIR.rstrip("/")] + list(parts))


# ============================================================
# PART 1: Ensemble voting demo (decisiontree_ch6.csv, small)
# Bootstrap N individual trees, compare their votes for a few
# real test rows against a single Decision Tree's prediction.
# ============================================================

df = pd.read_csv(dataset_path("buku1", "ch6", "decisiontree_ch6.csv"))
encoding = {"mesin": {"bensin": 0, "diesel": 1}, "penggerak": {"depan": 0, "belakang": 1}}
df_enc = df.replace(encoding)
df_enc.set_index("ID", inplace=True)

X = df_enc[["mesin", "bangku", "penggerak"]]
y = df_enc["label"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

single_tree = DecisionTreeClassifier(random_state=1, max_depth=3)
single_tree.fit(X_train, y_train)
single_pred = single_tree.predict(X_test)

N_TREES = 7
rng = np.random.RandomState(7)
mini_trees_preds = []
for t in range(N_TREES):
    boot_idx = rng.choice(len(X_train), size=len(X_train), replace=True)
    Xb, yb = X_train.iloc[boot_idx], y_train.iloc[boot_idx]
    feat_subset = list(rng.choice(X.columns, size=2, replace=False))
    t_model = DecisionTreeClassifier(random_state=t, max_depth=3)
    t_model.fit(Xb[feat_subset], yb)
    preds = t_model.predict(X_test[feat_subset])
    mini_trees_preds.append({"features": feat_subset, "preds": list(preds)})

rf_small = RandomForestClassifier(n_estimators=100, random_state=42)
rf_small.fit(X_train, y_train)
rf_small_pred = rf_small.predict(X_test)
rf_small_acc = float(rf_small.score(X_test, y_test))
single_acc = float(single_tree.score(X_test, y_test))

ensemble_demo = {
    "test_rows": [
        {"mesin": row.mesin, "bangku": int(row.bangku), "penggerak": row.penggerak, "actual": actual}
        for row, actual in zip(df.loc[X_test.index].itertuples(), y_test.tolist())
    ],
    "single_tree_pred": list(single_pred),
    "single_tree_acc": round(single_acc, 4),
    "mini_trees": mini_trees_preds,
    "rf_pred": list(rf_small_pred),
    "rf_acc": round(rf_small_acc, 4),
}

# ============================================================
# PART 2: Adult census dataset - feature importance + metrics
# ============================================================

cols = [
    "age", "workclass", "fnlwgt", "education", "education-num", "marital-status",
    "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss",
    "hrs-per-week", "native", "income",
]
adult = pd.read_csv(dataset_path("buku1", "adult", "adult.data"), header=None, names=cols)
adult.columns = [c.strip() for c in adult.columns]
for c in adult.select_dtypes(include="object").columns:
    adult[c] = adult[c].str.strip()

le_cols = ["workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native"]
for c in le_cols:
    adult[c + "_code"] = LabelEncoder().fit_transform(adult[c])

feature_cols = ["age", "education-num", "capital-gain", "capital-loss", "hrs-per-week"] + [c + "_code" for c in le_cols]
Xa = adult[feature_cols]
ya = adult["income"]

Xa_train, Xa_test, ya_train, ya_test = train_test_split(Xa, ya, test_size=0.2, random_state=0)
rf = RandomForestClassifier(random_state=0)
rf.fit(Xa_train, ya_train)
ya_pred = rf.predict(Xa_test)

report = classification_report(ya_test, ya_pred, output_dict=True)
importances = sorted(
    zip(feature_cols, rf.feature_importances_), key=lambda t: t[1], reverse=True
)

adult_out = {
    "n_rows": int(len(adult)),
    "accuracy": round(float(report["accuracy"]), 4),
    "report": {
        cls: {k: round(float(v), 4) for k, v in vals.items()}
        for cls, vals in report.items()
        if cls in ("<=50K", ">50K")
    },
    "feature_importance": [{"feature": f, "importance": round(float(imp), 4)} for f, imp in importances],
}

data = {"ensemble_demo": ensemble_demo, "adult": adult_out}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_rf_data.py\n"
js += "// Random Forest data for KupasAI ML Week 6 - decisiontree_ch6.csv + UCI Adult census\n\n"
js += "const RF_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("Single tree acc:", single_acc, "RF acc:", rf_small_acc)
print("Adult accuracy:", report["accuracy"])
print("Top features:", importances[:5])
print("Written:", outpath)
