// Auto-generated by generate_rnn_data.py
// RNN visualization data for KupasAI NLP Week 2-4

const RNN_DATA = {
  "vocab": {
    "saya": [
      0.0,
      0.0,
      0.0,
      0.3,
      0.1
    ],
    "dia": [
      0.0,
      0.0,
      0.0,
      0.2,
      0.1
    ],
    "aku": [
      0.0,
      0.0,
      0.0,
      0.2,
      0.1
    ],
    "kamu": [
      0.0,
      0.1,
      0.0,
      0.1,
      0.1
    ],
    "suka": [
      0.0,
      0.8,
      0.4,
      0.0,
      0.5
    ],
    "cinta": [
      0.0,
      0.9,
      0.0,
      0.0,
      0.8
    ],
    "benci": [
      0.0,
      -0.8,
      0.0,
      0.0,
      0.6
    ],
    "ketidakadilan": [
      0.0,
      -0.7,
      0.0,
      0.3,
      0.5
    ],
    "belajar": [
      0.0,
      0.3,
      0.7,
      0.3,
      0.3
    ],
    "indonesia": [
      0.0,
      0.1,
      0.0,
      0.4,
      0.2
    ],
    "makan": [
      0.1,
      0.3,
      0.9,
      -0.2,
      0.3
    ],
    "tidur": [
      0.0,
      0.2,
      -0.3,
      -0.3,
      0.1
    ],
    "buku": [
      0.0,
      0.1,
      -0.2,
      0.4,
      0.0
    ],
    "bagus": [
      0.0,
      0.9,
      0.1,
      0.2,
      0.7
    ],
    "jelek": [
      0.0,
      -0.8,
      0.0,
      0.0,
      0.6
    ],
    "guru": [
      0.3,
      0.3,
      0.5,
      0.6,
      0.2
    ],
    "sekolah": [
      0.0,
      0.2,
      0.3,
      0.5,
      0.2
    ],
    "main": [
      0.1,
      0.7,
      0.8,
      -0.3,
      0.5
    ],
    "kerja": [
      0.2,
      0.2,
      0.9,
      0.4,
      0.4
    ],
    "senang": [
      0.0,
      0.9,
      0.0,
      0.0,
      0.7
    ],
    "sedih": [
      0.0,
      -0.8,
      0.0,
      0.0,
      0.6
    ],
    "kopi": [
      0.0,
      0.4,
      0.2,
      -0.1,
      0.3
    ],
    "film": [
      0.0,
      0.3,
      -0.1,
      -0.2,
      0.3
    ]
  },
  "embed_dim": 5,
  "hidden_dim": 4,
  "weights": {
    "W_xh": [
      [
        0.0,
        0.0,
        0.0,
        0.0
      ],
      [
        1.5,
        0.2,
        0.1,
        0.0
      ],
      [
        0.1,
        0.0,
        0.8,
        0.1
      ],
      [
        0.0,
        0.1,
        0.0,
        0.5
      ],
      [
        0.0,
        0.0,
        0.0,
        0.3
      ]
    ],
    "W_hh": [
      [
        0.85,
        0.0,
        0.0,
        0.0
      ],
      [
        0.0,
        0.7,
        0.0,
        0.0
      ],
      [
        0.0,
        0.0,
        0.7,
        0.0
      ],
      [
        0.0,
        0.0,
        0.0,
        0.7
      ]
    ],
    "W_hy": [
      [
        2.5,
        -2.5
      ],
      [
        0.2,
        0.1
      ],
      [
        0.1,
        0.1
      ],
      [
        0.1,
        0.2
      ]
    ]
  },
  "sentences": [
    {
      "words": [
        "saya",
        "suka",
        "belajar"
      ],
      "states": [
        {
          "word": "saya",
          "input": [
            0.0,
            0.0,
            0.0,
            0.3,
            0.1
          ],
          "hidden_pre": [
            0.0,
            0.03,
            0.0,
            0.18
          ],
          "hidden": [
            0.0,
            0.03,
            0.0,
            0.178
          ],
          "output": [
            0.496,
            0.504
          ]
        },
        {
          "word": "suka",
          "input": [
            0.0,
            0.8,
            0.4,
            0.0,
            0.5
          ],
          "hidden_pre": [
            1.24,
            0.181,
            0.4,
            0.315
          ],
          "hidden": [
            0.845,
            0.179,
            0.38,
            0.305
          ],
          "output": [
            0.985,
            0.015
          ]
        },
        {
          "word": "belajar",
          "input": [
            0.0,
            0.3,
            0.7,
            0.3,
            0.3
          ],
          "hidden_pre": [
            1.239,
            0.215,
            0.856,
            0.523
          ],
          "hidden": [
            0.845,
            0.212,
            0.694,
            0.48
          ],
          "output": [
            0.985,
            0.015
          ]
        }
      ]
    },
    {
      "words": [
        "dia",
        "benci",
        "ketidakadilan"
      ],
      "states": [
        {
          "word": "dia",
          "input": [
            0.0,
            0.0,
            0.0,
            0.2,
            0.1
          ],
          "hidden_pre": [
            0.0,
            0.02,
            0.0,
            0.13
          ],
          "hidden": [
            0.0,
            0.02,
            0.0,
            0.129
          ],
          "output": [
            0.497,
            0.503
          ]
        },
        {
          "word": "benci",
          "input": [
            0.0,
            -0.8,
            0.0,
            0.0,
            0.6
          ],
          "hidden_pre": [
            -1.2,
            -0.146,
            -0.08,
            0.27
          ],
          "hidden": [
            -0.834,
            -0.145,
            -0.08,
            0.264
          ],
          "output": [
            0.015,
            0.985
          ]
        },
        {
          "word": "ketidakadilan",
          "input": [
            0.0,
            -0.7,
            0.0,
            0.3,
            0.5
          ],
          "hidden_pre": [
            -1.759,
            -0.211,
            -0.126,
            0.485
          ],
          "hidden": [
            -0.942,
            -0.208,
            -0.125,
            0.45
          ],
          "output": [
            0.008,
            0.992
          ]
        }
      ]
    },
    {
      "words": [
        "aku",
        "cinta",
        "indonesia"
      ],
      "states": [
        {
          "word": "aku",
          "input": [
            0.0,
            0.0,
            0.0,
            0.2,
            0.1
          ],
          "hidden_pre": [
            0.0,
            0.02,
            0.0,
            0.13
          ],
          "hidden": [
            0.0,
            0.02,
            0.0,
            0.129
          ],
          "output": [
            0.497,
            0.503
          ]
        },
        {
          "word": "cinta",
          "input": [
            0.0,
            0.9,
            0.0,
            0.0,
            0.8
          ],
          "hidden_pre": [
            1.35,
            0.194,
            0.09,
            0.33
          ],
          "hidden": [
            0.874,
            0.192,
            0.09,
            0.319
          ],
          "output": [
            0.987,
            0.013
          ]
        },
        {
          "word": "indonesia",
          "input": [
            0.0,
            0.1,
            0.0,
            0.4,
            0.2
          ],
          "hidden_pre": [
            0.893,
            0.194,
            0.073,
            0.483
          ],
          "hidden": [
            0.713,
            0.192,
            0.073,
            0.449
          ],
          "output": [
            0.972,
            0.028
          ]
        }
      ]
    }
  ],
  "gradient_data": {
    "5": {
      "rnn": [
        0.9688,
        1.1594,
        0.4797,
        0.2358,
        0.215
      ],
      "lstm": [
        2.2306,
        3.1025,
        4.4304,
        7.8716,
        12.4096
      ]
    },
    "10": {
      "rnn": [
        1.699,
        1.8022,
        1.6422,
        1.2668,
        0.8378,
        0.4937,
        0.3839,
        0.435,
        0.4448,
        0.3978
      ],
      "lstm": [
        1.9642,
        1.9753,
        1.5548,
        2.1766,
        2.2122,
        2.7362,
        3.4585,
        3.7093,
        5.5411,
        7.4554
      ]
    },
    "15": {
      "rnn": [
        1.5791,
        1.5682,
        2.2197,
        2.8023,
        3.6827,
        4.7647,
        6.1782,
        7.9843,
        10.3111,
        13.3022,
        17.1533,
        22.1115,
        28.4974,
        36.7228,
        47.319
      ],
      "lstm": [
        2.5589,
        3.3495,
        5.0794,
        6.5499,
        9.8229,
        15.1745,
        22.3897,
        33.0845,
        50.4867,
        76.5129,
        114.3529,
        172.6203,
        261.5482,
        394.0016,
        593.545
      ]
    },
    "20": {
      "rnn": [
        0.6368,
        0.2546,
        0.1797,
        0.0882,
        0.0722,
        0.0582,
        0.0436,
        0.0334,
        0.0259,
        0.0199,
        0.0153,
        0.0118,
        0.009,
        0.007,
        0.0054,
        0.0041,
        0.0032,
        0.0024,
        0.0019,
        0.0014
      ],
      "lstm": [
        2.7225,
        4.1075,
        6.377,
        9.648,
        13.9063,
        20.1769,
        29.4982,
        44.3806,
        67.0586,
        103.4279,
        158.7091,
        245.9944,
        379.2821,
        587.3836,
        907.1528,
        1403.4159,
        2169.0113,
        3353.8996,
        5185.0886,
        8016.269
      ]
    }
  },
  "representations": {
    "sentences": [
      {
        "label": "saya suka belajar",
        "words": [
          "saya",
          "suka",
          "belajar"
        ]
      },
      {
        "label": "dia benci ketidakadilan",
        "words": [
          "dia",
          "benci",
          "ketidakadilan"
        ]
      },
      {
        "label": "aku cinta indonesia",
        "words": [
          "aku",
          "cinta",
          "indonesia"
        ]
      },
      {
        "label": "belajar suka saya",
        "words": [
          "belajar",
          "suka",
          "saya"
        ]
      },
      {
        "label": "ketidakadilan benci dia",
        "words": [
          "ketidakadilan",
          "benci",
          "dia"
        ]
      },
      {
        "label": "indonesia cinta aku",
        "words": [
          "indonesia",
          "cinta",
          "aku"
        ]
      },
      {
        "label": "aku suka belajar",
        "words": [
          "aku",
          "suka",
          "belajar"
        ]
      },
      {
        "label": "saya benci ketidakadilan",
        "words": [
          "saya",
          "benci",
          "ketidakadilan"
        ]
      },
      {
        "label": "dia cinta indonesia",
        "words": [
          "dia",
          "cinta",
          "indonesia"
        ]
      },
      {
        "label": "aku benci belajar",
        "words": [
          "aku",
          "benci",
          "belajar"
        ]
      },
      {
        "label": "saya cinta belajar",
        "words": [
          "saya",
          "cinta",
          "belajar"
        ]
      }
    ],
    "methods": {
      "bow": {
        "label": "Bag-of-Words",
        "points": [
          {
            "label": "saya suka belajar",
            "x": -1.0,
            "y": 0.9339
          },
          {
            "label": "dia benci ketidakadilan",
            "x": 1.0,
            "y": 0.7228
          },
          {
            "label": "aku cinta indonesia",
            "x": -0.2235,
            "y": -1.0
          },
          {
            "label": "belajar suka saya",
            "x": -1.0,
            "y": 0.9339
          },
          {
            "label": "ketidakadilan benci dia",
            "x": 1.0,
            "y": 0.7228
          },
          {
            "label": "indonesia cinta aku",
            "x": -0.2235,
            "y": -1.0
          },
          {
            "label": "aku suka belajar",
            "x": -0.9227,
            "y": 0.3757
          },
          {
            "label": "saya benci ketidakadilan",
            "x": 0.4213,
            "y": 1.0
          },
          {
            "label": "dia cinta indonesia",
            "x": 0.278,
            "y": -0.7189
          },
          {
            "label": "aku benci belajar",
            "x": -0.2477,
            "y": 0.388
          },
          {
            "label": "saya cinta belajar",
            "x": -0.6865,
            "y": 0.2729
          }
        ]
      },
      "avg": {
        "label": "Average Vectors",
        "points": [
          {
            "label": "saya suka belajar",
            "x": -1.0,
            "y": -0.139
          },
          {
            "label": "dia benci ketidakadilan",
            "x": 1.0,
            "y": 0.5092
          },
          {
            "label": "aku cinta indonesia",
            "x": 0.0342,
            "y": -1.0
          },
          {
            "label": "belajar suka saya",
            "x": -1.0,
            "y": -0.139
          },
          {
            "label": "ketidakadilan benci dia",
            "x": 1.0,
            "y": 0.5092
          },
          {
            "label": "indonesia cinta aku",
            "x": 0.0342,
            "y": -1.0
          },
          {
            "label": "aku suka belajar",
            "x": -0.7955,
            "y": 1.0
          },
          {
            "label": "saya benci ketidakadilan",
            "x": 0.7955,
            "y": -0.6298
          },
          {
            "label": "dia cinta indonesia",
            "x": 0.0342,
            "y": -1.0
          },
          {
            "label": "aku benci belajar",
            "x": -0.0204,
            "y": 0.977
          },
          {
            "label": "saya cinta belajar",
            "x": -0.1568,
            "y": -0.8589
          }
        ]
      },
      "rnn": {
        "label": "RNN Hidden State",
        "points": [
          {
            "label": "saya suka belajar",
            "x": -0.9832,
            "y": -0.5107
          },
          {
            "label": "dia benci ketidakadilan",
            "x": 0.9313,
            "y": -0.7489
          },
          {
            "label": "aku cinta indonesia",
            "x": -0.352,
            "y": 0.1474
          },
          {
            "label": "belajar suka saya",
            "x": -0.4694,
            "y": 0.3859
          },
          {
            "label": "ketidakadilan benci dia",
            "x": 1.0,
            "y": 0.5618
          },
          {
            "label": "indonesia cinta aku",
            "x": -0.0776,
            "y": 1.0
          },
          {
            "label": "aku suka belajar",
            "x": -0.9189,
            "y": -0.2738
          },
          {
            "label": "saya benci ketidakadilan",
            "x": 0.8635,
            "y": -1.0
          },
          {
            "label": "dia cinta indonesia",
            "x": -0.352,
            "y": 0.1474
          },
          {
            "label": "aku benci belajar",
            "x": -0.0844,
            "y": -0.6783
          },
          {
            "label": "saya cinta belajar",
            "x": -1.0,
            "y": -0.78
          }
        ]
      }
    },
    "swap_pairs": [
      {
        "a_idx": 0,
        "b_idx": 3,
        "label_a": "saya suka belajar",
        "label_b": "belajar suka saya"
      }
    ]
  }
};
