// Auto-generated by generate_rnn_data.py
// RNN visualization data for KupasAI NLP Week 2-4

const RNN_DATA = {
  "vocab": {
    "saya": [
      0.0,
      0.0,
      0.0,
      0.3,
      0.1
    ],
    "kamu": [
      0.0,
      0.1,
      0.0,
      0.1,
      0.1
    ],
    "suka": [
      0.0,
      0.7,
      0.4,
      0.0,
      0.5
    ],
    "benci": [
      0.0,
      -0.7,
      0.0,
      0.0,
      0.6
    ],
    "makan": [
      0.1,
      0.3,
      0.9,
      -0.2,
      0.3
    ],
    "belajar": [
      0.0,
      0.4,
      0.7,
      0.3,
      0.4
    ],
    "tidur": [
      0.0,
      0.2,
      -0.3,
      -0.3,
      0.1
    ],
    "buku": [
      0.0,
      0.1,
      -0.2,
      0.4,
      0.0
    ],
    "bagus": [
      0.0,
      0.9,
      0.1,
      0.2,
      0.7
    ],
    "jelek": [
      0.0,
      -0.8,
      0.0,
      0.0,
      0.6
    ],
    "guru": [
      0.3,
      0.3,
      0.5,
      0.6,
      0.2
    ],
    "sekolah": [
      0.0,
      0.2,
      0.3,
      0.5,
      0.2
    ],
    "main": [
      0.1,
      0.7,
      0.8,
      -0.3,
      0.5
    ],
    "kerja": [
      0.2,
      0.2,
      0.9,
      0.4,
      0.4
    ],
    "senang": [
      0.0,
      0.9,
      0.0,
      0.0,
      0.7
    ],
    "sedih": [
      0.0,
      -0.8,
      0.0,
      0.0,
      0.6
    ],
    "kopi": [
      0.0,
      0.4,
      0.2,
      -0.1,
      0.3
    ],
    "film": [
      0.0,
      0.3,
      -0.1,
      -0.2,
      0.3
    ]
  },
  "embed_dim": 5,
  "hidden_dim": 4,
  "weights": {
    "W_xh": [
      [
        0.248,
        -0.069,
        0.324,
        0.762
      ],
      [
        -0.117,
        -0.117,
        0.79,
        0.384
      ],
      [
        -0.235,
        0.271,
        -0.232,
        -0.233
      ],
      [
        0.121,
        -0.957,
        -0.862,
        -0.281
      ],
      [
        -0.506,
        0.157,
        -0.454,
        -0.706
      ]
    ],
    "W_hh": [
      [
        0.733,
        -0.113,
        0.034,
        -0.712
      ],
      [
        -0.272,
        0.055,
        -0.575,
        0.188
      ],
      [
        -0.3,
        -0.146,
        -0.301,
        0.926
      ],
      [
        -0.007,
        -0.529,
        0.411,
        -0.61
      ]
    ],
    "W_hy": [
      [
        0.369,
        0.086
      ],
      [
        -0.058,
        -0.151
      ],
      [
        -0.739,
        -0.36
      ],
      [
        -0.23,
        0.529
      ]
    ]
  },
  "sentences": [
    {
      "words": [
        "saya",
        "suka",
        "belajar"
      ],
      "states": [
        {
          "word": "saya",
          "input": [
            0.0,
            0.0,
            0.0,
            0.3,
            0.1
          ],
          "hidden_pre": [
            0.007,
            -0.467,
            -0.437,
            -0.135
          ],
          "hidden": [
            0.007,
            -0.436,
            -0.411,
            -0.134
          ],
          "output": [
            0.606,
            0.394
          ]
        },
        {
          "word": "suka",
          "input": [
            0.0,
            0.7,
            0.4,
            0.0,
            0.5
          ],
          "hidden_pre": [
            -0.16,
            0.015,
            0.42,
            -0.543
          ],
          "hidden": [
            -0.159,
            0.015,
            0.397,
            -0.495
          ],
          "output": [
            0.597,
            0.403
          ]
        },
        {
          "word": "belajar",
          "input": [
            0.0,
            0.4,
            0.7,
            0.3,
            0.4
          ],
          "hidden_pre": [
            -0.593,
            -0.054,
            -0.757,
            0.429
          ],
          "hidden": [
            -0.532,
            -0.054,
            -0.639,
            0.405
          ],
          "output": [
            0.498,
            0.502
          ]
        }
      ]
    },
    {
      "words": [
        "kamu",
        "benci",
        "jelek"
      ],
      "states": [
        {
          "word": "kamu",
          "input": [
            0.0,
            0.1,
            0.0,
            0.1,
            0.1
          ],
          "hidden_pre": [
            -0.029,
            -0.288,
            -0.186,
            -0.041
          ],
          "hidden": [
            -0.029,
            -0.28,
            -0.183,
            -0.041
          ],
          "output": [
            0.569,
            0.431
          ]
        },
        {
          "word": "benci",
          "input": [
            0.0,
            -0.7,
            0.0,
            0.0,
            0.6
          ],
          "hidden_pre": [
            -0.091,
            0.016,
            -0.759,
            -0.849
          ],
          "hidden": [
            -0.091,
            0.016,
            -0.641,
            -0.691
          ],
          "output": [
            0.722,
            0.278
          ]
        },
        {
          "word": "jelek",
          "input": [
            0.0,
            -0.8,
            0.0,
            0.0,
            0.6
          ],
          "hidden_pre": [
            -0.063,
            0.462,
            -1.141,
            -0.815
          ],
          "hidden": [
            -0.063,
            0.432,
            -0.815,
            -0.672
          ],
          "output": [
            0.741,
            0.259
          ]
        }
      ]
    },
    {
      "words": [
        "guru",
        "bagus",
        "belajar"
      ],
      "states": [
        {
          "word": "guru",
          "input": [
            0.3,
            0.3,
            0.5,
            0.6,
            0.2
          ],
          "hidden_pre": [
            -0.086,
            -0.659,
            -0.523,
            -0.063
          ],
          "hidden": [
            -0.086,
            -0.578,
            -0.48,
            -0.063
          ],
          "output": [
            0.59,
            0.41
          ]
        },
        {
          "word": "bagus",
          "input": [
            0.0,
            0.9,
            0.1,
            0.2,
            0.7
          ],
          "hidden_pre": [
            -0.199,
            -0.275,
            0.512,
            -0.662
          ],
          "hidden": [
            -0.197,
            -0.268,
            0.472,
            -0.58
          ],
          "output": [
            0.597,
            0.403
          ]
        },
        {
          "word": "belajar",
          "input": [
            0.0,
            0.4,
            0.7,
            0.3,
            0.4
          ],
          "hidden_pre": [
            -0.565,
            -0.032,
            -0.652,
            0.524
          ],
          "hidden": [
            -0.512,
            -0.032,
            -0.573,
            0.481
          ],
          "output": [
            0.479,
            0.521
          ]
        }
      ]
    }
  ],
  "gradient_data": {
    "5": {
      "rnn": [
        0.9013,
        0.8496,
        0.8275,
        0.4427,
        0.191
      ],
      "lstm": [
        2.2763,
        2.9313,
        6.2026,
        10.101,
        11.6583
      ]
    },
    "10": {
      "rnn": [
        1.2661,
        0.7759,
        0.297,
        0.1539,
        0.1203,
        0.096,
        0.0535,
        0.0213,
        0.0143,
        0.0113
      ],
      "lstm": [
        2.3109,
        5.7665,
        11.8149,
        22.2639,
        47.0304,
        106.1146,
        229.9634,
        489.9197,
        1056.9968,
        2294.4131
      ]
    },
    "15": {
      "rnn": [
        0.999,
        0.7096,
        0.5469,
        0.304,
        0.2115,
        0.094,
        0.0697,
        0.0481,
        0.0343,
        0.024,
        0.0175,
        0.0121,
        0.0088,
        0.0062,
        0.0044
      ],
      "lstm": [
        3.4218,
        3.0423,
        2.2021,
        4.4319,
        5.5722,
        4.4575,
        7.8124,
        11.0928,
        13.8655,
        25.3544,
        34.6951,
        59.2998,
        103.1664,
        157.2754,
        273.3544
      ]
    },
    "20": {
      "rnn": [
        1.301,
        0.6115,
        0.4198,
        0.4753,
        0.4607,
        0.3993,
        0.3351,
        0.2657,
        0.2039,
        0.1518,
        0.1098,
        0.0773,
        0.053,
        0.0353,
        0.0227,
        0.0141,
        0.0083,
        0.0046,
        0.0023,
        0.001
      ],
      "lstm": [
        1.9159,
        2.3879,
        2.9293,
        3.4876,
        4.1917,
        5.2876,
        6.902,
        9.2554,
        13.175,
        19.1625,
        25.5634,
        29.1064,
        30.5633,
        43.2285,
        70.2884,
        94.7825,
        120.5864,
        210.5652,
        376.3692,
        526.4033
      ]
    }
  },
  "representations": {
    "sentences": [
      {
        "label": "saya suka belajar",
        "words": [
          "saya",
          "suka",
          "belajar"
        ]
      },
      {
        "label": "saya benci belajar",
        "words": [
          "saya",
          "benci",
          "belajar"
        ]
      },
      {
        "label": "saya suka main",
        "words": [
          "saya",
          "suka",
          "main"
        ]
      },
      {
        "label": "saya benci main",
        "words": [
          "saya",
          "benci",
          "main"
        ]
      },
      {
        "label": "kamu suka belajar",
        "words": [
          "kamu",
          "suka",
          "belajar"
        ]
      },
      {
        "label": "kamu benci belajar",
        "words": [
          "kamu",
          "benci",
          "belajar"
        ]
      },
      {
        "label": "guru bagus belajar",
        "words": [
          "guru",
          "bagus",
          "belajar"
        ]
      },
      {
        "label": "belajar suka saya (dibalik)",
        "words": [
          "belajar",
          "suka",
          "saya"
        ]
      },
      {
        "label": "suka saya belajar (acak)",
        "words": [
          "suka",
          "saya",
          "belajar"
        ]
      },
      {
        "label": "kamu senang kopi",
        "words": [
          "kamu",
          "senang",
          "kopi"
        ]
      },
      {
        "label": "saya makan bagus",
        "words": [
          "saya",
          "makan",
          "bagus"
        ]
      },
      {
        "label": "film bagus senang",
        "words": [
          "film",
          "bagus",
          "senang"
        ]
      }
    ],
    "methods": {
      "bow": {
        "label": "Bag-of-Words",
        "points": [
          {
            "label": "saya suka belajar",
            "x": -1.0,
            "y": -0.1135
          },
          {
            "label": "saya benci belajar",
            "x": -0.8601,
            "y": -0.1292
          },
          {
            "label": "saya suka main",
            "x": -0.9839,
            "y": 0.1445
          },
          {
            "label": "saya benci main",
            "x": -0.8441,
            "y": 0.1288
          },
          {
            "label": "kamu suka belajar",
            "x": -0.5335,
            "y": -0.7154
          },
          {
            "label": "kamu benci belajar",
            "x": -0.3936,
            "y": -0.7312
          },
          {
            "label": "guru bagus belajar",
            "x": -0.0298,
            "y": 0.3764
          },
          {
            "label": "belajar suka saya (dibalik)",
            "x": -1.0,
            "y": -0.1135
          },
          {
            "label": "suka saya belajar (acak)",
            "x": -1.0,
            "y": -0.1135
          },
          {
            "label": "kamu senang kopi",
            "x": 0.8207,
            "y": -1.0
          },
          {
            "label": "saya makan bagus",
            "x": -0.1983,
            "y": 1.0
          },
          {
            "label": "film bagus senang",
            "x": 1.0,
            "y": 0.4865
          }
        ]
      },
      "avg": {
        "label": "Average Vectors",
        "points": [
          {
            "label": "saya suka belajar",
            "x": -0.5512,
            "y": -0.5859
          },
          {
            "label": "saya benci belajar",
            "x": -0.3595,
            "y": -0.985
          },
          {
            "label": "saya suka main",
            "x": -0.2949,
            "y": -0.1999
          },
          {
            "label": "saya benci main",
            "x": -0.1032,
            "y": -0.5989
          },
          {
            "label": "kamu suka belajar",
            "x": -0.4357,
            "y": -0.6009
          },
          {
            "label": "kamu benci belajar",
            "x": -0.244,
            "y": -1.0
          },
          {
            "label": "guru bagus belajar",
            "x": -1.0,
            "y": 1.0
          },
          {
            "label": "belajar suka saya (dibalik)",
            "x": -0.5512,
            "y": -0.5859
          },
          {
            "label": "suka saya belajar (acak)",
            "x": -0.5512,
            "y": -0.5859
          },
          {
            "label": "kamu senang kopi",
            "x": 0.365,
            "y": -0.576
          },
          {
            "label": "saya makan bagus",
            "x": -0.3629,
            "y": -0.2087
          },
          {
            "label": "film bagus senang",
            "x": 1.0,
            "y": 0.3604
          }
        ]
      },
      "rnn": {
        "label": "RNN Hidden State",
        "points": [
          {
            "label": "saya suka belajar",
            "x": 0.731,
            "y": 0.6473
          },
          {
            "label": "saya benci belajar",
            "x": -1.0,
            "y": 0.4259
          },
          {
            "label": "saya suka main",
            "x": 0.9893,
            "y": -0.7873
          },
          {
            "label": "saya benci main",
            "x": -0.5506,
            "y": -1.0
          },
          {
            "label": "kamu suka belajar",
            "x": 0.7424,
            "y": 0.5811
          },
          {
            "label": "kamu benci belajar",
            "x": -0.8756,
            "y": 0.3259
          },
          {
            "label": "guru bagus belajar",
            "x": 0.7414,
            "y": 0.5515
          },
          {
            "label": "belajar suka saya (dibalik)",
            "x": 0.546,
            "y": 1.0
          },
          {
            "label": "suka saya belajar (acak)",
            "x": -0.652,
            "y": 0.2021
          },
          {
            "label": "kamu senang kopi",
            "x": 0.8164,
            "y": -0.1925
          },
          {
            "label": "saya makan bagus",
            "x": 1.0,
            "y": 0.3438
          },
          {
            "label": "film bagus senang",
            "x": 0.8653,
            "y": -0.663
          }
        ]
      }
    },
    "swap_pairs": [
      {
        "a_idx": 0,
        "b_idx": 7,
        "label_a": "saya suka belajar",
        "label_b": "belajar suka saya (dibalik)"
      }
    ]
  }
};
