#!/usr/bin/env python3
"""
KupasAI - Linear Regression Data Generator
Uses the real datasets from Modul 3 (bensin.csv, MLG_data.csv) - same
source repo as the course notebook, not synthetic data.
"""

import json
import os

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

HERE = os.path.dirname(os.path.abspath(__file__))

# Reads straight from the course's dataset repo on GitHub, same as the
# notebook. Set DASAR_ML_DIR to a local clone of that repo to read from
# disk instead (e.g. while offline).
DATASET_DIR = os.environ.get(
    "DASAR_ML_DIR",
    "https://raw.githubusercontent.com/FeliksMakarios/dasar-machine-learning/main",
)


def dataset_path(*parts):
    return "/".join([DATASET_DIR.rstrip("/")] + list(parts))


# ============================================================
# SIMPLE LINEAR REGRESSION: bensin.csv (Liter -> Kilometer)
# ============================================================

df = pd.read_csv(dataset_path("buku1", "ch4", "bensin.csv"), encoding="utf-8-sig")

X = df["Liter"].values.reshape(-1, 1)
y = df["Kilometer"].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)
r2 = model.score(X_test, y_test)

simple = {
    "points": [{"x": float(r[0]), "y": float(v)} for r, v in zip(X, y)],
    "slope": round(float(model.coef_[0]), 4),
    "intercept": round(float(model.intercept_), 4),
    "r2": round(float(r2), 4),
    "x_min": float(df["Liter"].min()),
    "x_max": float(df["Liter"].max()),
    "y_min": float(df["Kilometer"].min()),
    "y_max": float(df["Kilometer"].max()),
}

# ============================================================
# MULTIPLE LINEAR REGRESSION: MLG_data.csv
# ============================================================

df2 = pd.read_csv(dataset_path("buku1", "MLG_data.csv"), index_col=0)

corr = df2.corr(method="pearson").round(4)
corr_matrix = {
    "columns": list(corr.columns),
    "values": corr.values.tolist(),
}

feature_sets = {
    "1": ["Liter"],
    "2": ["Liter", "Penumpang"],
    "4": ["Liter", "Penumpang", "Bagasi", "Kecepatan"],
}

models_out = {}
for key, feats in feature_sets.items():
    Xm = df2[feats]
    ym = df2["Kilometer"]
    Xtr, Xte, ytr, yte = train_test_split(Xm, ym, test_size=0.2, random_state=0)
    m = LinearRegression()
    m.fit(Xtr, ytr)
    models_out[key] = {
        "features": feats,
        "intercept": round(float(m.intercept_), 3),
        "coef": [round(float(c), 3) for c in m.coef_],
        "r2": round(float(m.score(Xte, yte)), 4),
    }

data = {
    "simple": simple,
    "corr": corr_matrix,
    "multi": models_out,
}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_lr_data.py\n"
js += "// Linear Regression data for KupasAI ML Week 3 - dataset asli bensin.csv & MLG_data.csv\n\n"
js += "const LR_DATA = " + json.dumps(data, indent=2) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("Simple LR: slope=%.4f intercept=%.4f r2=%.4f" % (simple["slope"], simple["intercept"], simple["r2"]))
for k, v in models_out.items():
    print(k, "features:", v["features"], "coef:", v["coef"], "intercept:", v["intercept"], "r2:", v["r2"])
print("Written:", outpath)
