// Auto-generated by generate_embeddings.py
// Word embeddings for KupasAI NLP visualization

const EMBEDDING_DATA = {
  "dimensions": [
    "gender_maskulin",
    "status_kerajaan",
    "usia_muda",
    "keluarga_inti",
    "keluarga_luas",
    "otoritas",
    "pendidikan",
    "formalitas",
    "positif",
    "abstrak"
  ],
  "words": [
    {
      "word": "raja",
      "vector": [
        0.95,
        0.98,
        0.0,
        0.0,
        0.0,
        0.95,
        0.0,
        0.95,
        0.3,
        0.5
      ],
      "x": -1.0,
      "y": 0.0865,
      "category": "kerajaan"
    },
    {
      "word": "ratu",
      "vector": [
        -0.95,
        0.98,
        0.0,
        0.0,
        0.0,
        0.92,
        0.0,
        0.95,
        0.3,
        0.5
      ],
      "x": -0.847,
      "y": 0.1242,
      "category": "kerajaan"
    },
    {
      "word": "pangeran",
      "vector": [
        0.9,
        0.9,
        0.7,
        0.3,
        0.0,
        0.6,
        0.0,
        0.85,
        0.4,
        0.4
      ],
      "x": -0.548,
      "y": 0.1165,
      "category": "kerajaan"
    },
    {
      "word": "putri",
      "vector": [
        -0.9,
        0.9,
        0.7,
        0.3,
        0.0,
        0.55,
        0.0,
        0.85,
        0.4,
        0.4
      ],
      "x": -0.3901,
      "y": 0.1483,
      "category": "kerajaan"
    },
    {
      "word": "sultan",
      "vector": [
        0.92,
        0.85,
        0.0,
        0.0,
        0.0,
        0.93,
        0.2,
        0.9,
        0.2,
        0.5
      ],
      "x": -0.9521,
      "y": 0.0414,
      "category": "kerajaan"
    },
    {
      "word": "ayah",
      "vector": [
        0.9,
        0.0,
        -0.3,
        0.95,
        0.0,
        0.5,
        0.0,
        0.4,
        0.7,
        0.2
      ],
      "x": 0.2696,
      "y": 0.6942,
      "category": "keluarga"
    },
    {
      "word": "ibu",
      "vector": [
        -0.9,
        0.0,
        -0.3,
        0.95,
        0.0,
        0.48,
        0.0,
        0.4,
        0.8,
        0.2
      ],
      "x": 0.4147,
      "y": 0.7725,
      "category": "keluarga"
    },
    {
      "word": "anak",
      "vector": [
        0.0,
        0.0,
        0.9,
        0.9,
        0.0,
        0.0,
        0.2,
        0.2,
        0.8,
        0.1
      ],
      "x": 0.8017,
      "y": 0.4858,
      "category": "keluarga"
    },
    {
      "word": "putra",
      "vector": [
        0.85,
        0.0,
        0.8,
        0.85,
        0.0,
        0.1,
        0.0,
        0.5,
        0.6,
        0.2
      ],
      "x": 0.5298,
      "y": 0.3823,
      "category": "keluarga"
    },
    {
      "word": "putri_perempuan",
      "vector": [
        -0.85,
        0.0,
        0.8,
        0.85,
        0.0,
        0.08,
        0.0,
        0.5,
        0.6,
        0.2
      ],
      "x": 0.6627,
      "y": 0.4172,
      "category": "keluarga"
    },
    {
      "word": "kakek",
      "vector": [
        0.85,
        0.0,
        -0.9,
        0.3,
        0.9,
        0.4,
        0.0,
        0.45,
        0.7,
        0.2
      ],
      "x": 0.2845,
      "y": 0.9239,
      "category": "keluarga"
    },
    {
      "word": "nenek",
      "vector": [
        -0.85,
        0.0,
        -0.9,
        0.3,
        0.9,
        0.38,
        0.0,
        0.45,
        0.8,
        0.2
      ],
      "x": 0.4225,
      "y": 1.0,
      "category": "keluarga"
    },
    {
      "word": "paman",
      "vector": [
        0.88,
        0.0,
        -0.2,
        0.1,
        0.92,
        0.3,
        0.0,
        0.35,
        0.6,
        0.2
      ],
      "x": 0.4052,
      "y": 0.6595,
      "category": "keluarga"
    },
    {
      "word": "bibi",
      "vector": [
        -0.88,
        0.0,
        -0.2,
        0.1,
        0.92,
        0.28,
        0.0,
        0.35,
        0.7,
        0.2
      ],
      "x": 0.5475,
      "y": 0.737,
      "category": "keluarga"
    },
    {
      "word": "sepupu",
      "vector": [
        0.0,
        0.0,
        0.3,
        0.0,
        0.88,
        0.0,
        0.1,
        0.2,
        0.6,
        0.2
      ],
      "x": 0.7107,
      "y": 0.4596,
      "category": "keluarga"
    },
    {
      "word": "pria",
      "vector": [
        0.95,
        0.0,
        0.0,
        0.0,
        0.0,
        0.3,
        0.0,
        0.3,
        0.3,
        0.3
      ],
      "x": 0.2069,
      "y": -0.0154,
      "category": "gender"
    },
    {
      "word": "wanita",
      "vector": [
        -0.95,
        0.0,
        0.0,
        0.0,
        0.0,
        0.25,
        0.0,
        0.3,
        0.4,
        0.3
      ],
      "x": 0.3772,
      "y": 0.0598,
      "category": "gender"
    },
    {
      "word": "laki-laki",
      "vector": [
        0.93,
        0.0,
        0.2,
        0.0,
        0.0,
        0.2,
        0.0,
        0.15,
        0.3,
        0.2
      ],
      "x": 0.3793,
      "y": -0.0258,
      "category": "gender"
    },
    {
      "word": "perempuan",
      "vector": [
        -0.93,
        0.0,
        0.2,
        0.0,
        0.0,
        0.18,
        0.0,
        0.15,
        0.4,
        0.2
      ],
      "x": 0.5287,
      "y": 0.0539,
      "category": "gender"
    },
    {
      "word": "cowok",
      "vector": [
        0.9,
        0.0,
        0.5,
        0.0,
        0.0,
        0.0,
        0.0,
        -0.5,
        0.3,
        0.1
      ],
      "x": 0.8668,
      "y": -0.1744,
      "category": "gender"
    },
    {
      "word": "cewek",
      "vector": [
        -0.9,
        0.0,
        0.5,
        0.0,
        0.0,
        0.0,
        0.0,
        -0.5,
        0.4,
        0.1
      ],
      "x": 1.0,
      "y": -0.0924,
      "category": "gender"
    },
    {
      "word": "guru",
      "vector": [
        0.1,
        0.0,
        -0.2,
        0.0,
        0.0,
        0.45,
        0.92,
        0.6,
        0.7,
        0.3
      ],
      "x": -0.1794,
      "y": 0.3287,
      "category": "profesi"
    },
    {
      "word": "dosen",
      "vector": [
        0.15,
        0.0,
        -0.4,
        0.0,
        0.0,
        0.6,
        0.95,
        0.75,
        0.6,
        0.3
      ],
      "x": -0.3759,
      "y": 0.3791,
      "category": "profesi"
    },
    {
      "word": "dokter",
      "vector": [
        0.1,
        0.0,
        -0.1,
        0.0,
        0.0,
        0.7,
        0.6,
        0.8,
        0.6,
        0.3
      ],
      "x": -0.3499,
      "y": 0.3452,
      "category": "profesi"
    },
    {
      "word": "insinyur",
      "vector": [
        0.3,
        0.0,
        0.0,
        0.0,
        0.0,
        0.55,
        0.5,
        0.7,
        0.4,
        0.3
      ],
      "x": -0.2039,
      "y": 0.1896,
      "category": "profesi"
    },
    {
      "word": "presiden",
      "vector": [
        0.2,
        0.3,
        0.0,
        0.0,
        0.0,
        0.98,
        0.2,
        0.98,
        0.3,
        0.6
      ],
      "x": -0.7281,
      "y": 0.0581,
      "category": "profesi"
    },
    {
      "word": "menteri",
      "vector": [
        0.25,
        0.2,
        0.0,
        0.0,
        0.0,
        0.9,
        0.3,
        0.92,
        0.3,
        0.5
      ],
      "x": -0.6106,
      "y": 0.1064,
      "category": "profesi"
    },
    {
      "word": "perawat",
      "vector": [
        -0.4,
        0.0,
        0.1,
        0.0,
        0.0,
        0.45,
        0.6,
        0.6,
        0.8,
        0.3
      ],
      "x": -0.0387,
      "y": 0.3187,
      "category": "profesi"
    },
    {
      "word": "cinta",
      "vector": [
        -0.2,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.98,
        0.95
      ],
      "x": 0.5205,
      "y": -0.291,
      "category": "emosi"
    },
    {
      "word": "kasih",
      "vector": [
        -0.3,
        0.0,
        0.0,
        0.2,
        0.0,
        0.0,
        0.0,
        0.0,
        0.95,
        0.9
      ],
      "x": 0.5809,
      "y": -0.1884,
      "category": "emosi"
    },
    {
      "word": "benci",
      "vector": [
        0.1,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        -0.9,
        0.85
      ],
      "x": 0.4208,
      "y": -1.0,
      "category": "emosi"
    },
    {
      "word": "marah",
      "vector": [
        0.2,
        0.0,
        0.0,
        0.0,
        0.0,
        0.3,
        0.0,
        0.1,
        -0.7,
        0.75
      ],
      "x": 0.2157,
      "y": -0.7729,
      "category": "emosi"
    },
    {
      "word": "bahagia",
      "vector": [
        0.0,
        0.0,
        0.3,
        0.0,
        0.0,
        0.0,
        0.0,
        0.1,
        0.92,
        0.85
      ],
      "x": 0.4998,
      "y": -0.2774,
      "category": "emosi"
    },
    {
      "word": "sedih",
      "vector": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.1,
        -0.8,
        0.85
      ],
      "x": 0.3839,
      "y": -0.9358,
      "category": "emosi"
    },
    {
      "word": "takut",
      "vector": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        -0.6,
        0.8
      ],
      "x": 0.4537,
      "y": -0.8385,
      "category": "emosi"
    },
    {
      "word": "sekolah",
      "vector": [
        0.0,
        0.0,
        0.3,
        0.0,
        0.0,
        0.5,
        0.95,
        0.7,
        0.3,
        0.6
      ],
      "x": -0.2969,
      "y": -0.0992,
      "category": "institusi"
    },
    {
      "word": "universitas",
      "vector": [
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.7,
        0.98,
        0.85,
        0.3,
        0.65
      ],
      "x": -0.5331,
      "y": -0.0167,
      "category": "institusi"
    },
    {
      "word": "rumah",
      "vector": [
        0.0,
        0.0,
        0.0,
        0.5,
        0.3,
        0.0,
        0.0,
        0.2,
        0.5,
        0.3
      ],
      "x": 0.6831,
      "y": 0.3347,
      "category": "keluarga"
    },
    {
      "word": "istana",
      "vector": [
        0.1,
        0.85,
        0.0,
        0.0,
        0.0,
        0.92,
        0.0,
        0.95,
        0.3,
        0.55
      ],
      "x": -0.8709,
      "y": 0.0658,
      "category": "kerajaan"
    },
    {
      "word": "kerja",
      "vector": [
        0.1,
        0.0,
        0.0,
        0.0,
        0.0,
        0.4,
        0.3,
        0.5,
        0.2,
        0.4
      ],
      "x": 0.0142,
      "y": -0.0367,
      "category": "aksi"
    },
    {
      "word": "belajar",
      "vector": [
        0.0,
        0.0,
        0.5,
        0.0,
        0.0,
        0.0,
        0.9,
        0.4,
        0.5,
        0.4
      ],
      "x": 0.2293,
      "y": -0.0626,
      "category": "aksi"
    }
  ],
  "preset_analogies": [
    {
      "a": "raja",
      "b": "pria",
      "c": "wanita",
      "label": "raja - pria + wanita = ?",
      "result": "ratu",
      "similarity": 0.999
    },
    {
      "a": "pangeran",
      "b": "putra",
      "c": "putri_perempuan",
      "label": "pangeran - putra + putri = ?",
      "result": "putri",
      "similarity": 0.999
    },
    {
      "a": "ayah",
      "b": "pria",
      "c": "wanita",
      "label": "ayah - pria + wanita = ?",
      "result": "ibu",
      "similarity": 0.999
    },
    {
      "a": "kakek",
      "b": "paman",
      "c": "bibi",
      "label": "kakek - paman + bibi = ?",
      "result": "nenek",
      "similarity": 1.0
    },
    {
      "a": "raja",
      "b": "presiden",
      "c": "dosen",
      "label": "raja - presiden + dosen = ?",
      "result": "sultan",
      "similarity": 0.868
    }
  ],
  "pca_info": {
    "pc1_explained": 26.2,
    "pc2_explained": 19.3
  }
};
