"""Rebuild all nine advanced ML demonstrations from declared inputs.

Run from any directory. Training examples use half squared error as objective.
Displayed MSE is twice that objective, with averaging over output dimensions.
"""
from pathlib import Path
import json
import copy
import numpy as np
from sklearn.datasets import load_digits, make_circles
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier

ROOT = Path(__file__).resolve().parents[1]
SPEC = json.loads((ROOT/'scripts/advanced_inputs.json').read_text())
def clean(x):
    if isinstance(x, np.ndarray): return clean(x.tolist())
    if isinstance(x, dict): return {k:clean(v) for k,v in x.items()}
    if isinstance(x, (list,tuple)): return [clean(v) for v in x]
    if isinstance(x, (float,np.floating)): return round(float(x),8)
    if isinstance(x,np.integer): return int(x)
    return x
def write(topic,name,data,filename='data.js'):
    (ROOT/'ml-lanjut'/topic/filename).write_text('// Generated by scripts/generate_advanced.py. Seed 42 unless specified.\nvar '+name+' = '+json.dumps(clean(data),ensure_ascii=False,indent=2,allow_nan=False)+';\n')
def vec(x): return json.dumps(clean(x),ensure_ascii=False)

# Forward propagation: output-by-input orientation.
forward=SPEC['forward']
for s in forward['scenarios']:
    a=np.array([n['value'] for n in s['layers'][0]['nodes']])
    s['trace']=[]
    for w,layer in zip(s['weights'],s['layers'][1:]):
        b=np.array(w)@a
        s['trace'].append(vec(w)+' × '+vec(a)+' = '+vec(b))
        for n,v in zip(layer['nodes'],b): n['value']=float(v)
        a=b
write('forward-propagation','FORWARD_PROP_DATA',forward)

# One-dimensional gradient descent: log post-update weights AND errors.
w=.5; hot=[]; gd=[]
for i in range(1,11):
    w+=.01
    hot.append(dict(iter=i,weight=w,error=(.5*w-.8)**2))
w=.5
for i in range(1,11):
    w-=.5*(.5*w-.8)
    gd.append(dict(iter=i,weight=w,error=(.5*w-.8)**2))
w=.1; x=8.5; target=1.; alpha=.01; pred=x*w; delta=pred-target; new=w-alpha*x*delta
steps=[('Prediksi','pred = x × w',pred),('Delta','delta = pred − target',delta),('Gradien','grad = x × delta',x*delta),('Bobot baru','w baru = w − alpha × grad',new),('Prediksi baru','pred baru = x × w baru',x*new)]
write('gradient-descent','GD_DATA',dict(compare=dict(weight0=.5,input=.5,goal=.8,lr=.01,hot_cold=hot,gd=gd),oneIteration=dict(weight=w,input=x,goal=target,alpha=alpha,steps=[dict(name=f'{i+1}. {a}',formula=b,value=str(round(c,8))) for i,(a,b,c) in enumerate(steps)],errorBefore=delta**2,errorAfter=(x*new-target)**2),alphaPresets=[dict(label='Normal',input=.5,alpha=1),dict(label='Divergen',input=2,alpha=1),dict(label='Stabil',input=2,alpha=.1)]))

# Generalizing GD. Freeze comparison uses the same learning rate.
x=np.array([8.5,.65,1.2]); w0=np.array([.1,.2,-.1]); mi=dict(input=x,inputLabels=['toes','wlrec','nfans'])
for mode in ['normal','frozen']:
    w=w0.copy(); iters=[]
    for i in range(1,21):
        pred=x@w; delta=pred-1; grad=x*delta
        if mode=='frozen':grad[0]=0
        w-=.01*grad
        iters.append(dict(iter=i,pred=pred,error=delta**2,delta=delta,weight_deltas=grad.copy(),weights=w.copy()))
    mi[mode]=dict(alpha=.01,weights0=w0,iters=iters)
t=np.array([.1,1,.1]); w=np.array([.3,.2,.9]); pred=.65*w; delta=pred-t; grad=.65*delta
mo=dict(input=.65,inputLabel='wlrec',outputLabels=['hurt','win','sad'],true_=t,weights0=w,alpha=.1,pred=pred,error=delta**2,delta=delta,weight_deltas=grad,weights1=w-.1*grad)
w=np.array([[.1,.1,-.3],[.1,.2,0],[0,1.3,.1]]); pred=x@w; delta=pred-t; grad=np.outer(x,delta)
mio=dict(input=x,inputLabels=['toes','wlrec','nfans'],outputLabels=['hurt','win','sad'],true_=t,weights0=w,alpha=.01,pred=pred,error=delta**2,delta=delta,weight_deltas=grad,weights1=w-.01*grad)
write('generalizing-gd','GGD_DATA',dict(multiInput=mi,multiOutput=mo,multiInOut=mio))

# Streetlight: record online loss before each update explicitly.
rows=np.array([[1,0,1,0],[0,1,1,1],[0,0,1,0],[1,1,1,1],[0,1,1,1],[1,0,1,0]])
w0=np.array([.5,.48,-.7]);w=w0.copy(); single=[]
for i in range(1,21):
    pred=rows[0,:3]@w; w-=.1*rows[0,:3]*pred
    if i in [1,2,3,5,10,20]:single.append(dict(iter=i,pred=pred,error=pred**2,weights=w.copy()))
w=w0.copy(); logs=[]; selected=[]
for epoch in range(1,41):
    error=0.
    for row in rows:
        delta=row[:3]@w-row[3];error+=delta**2;w-=.1*row[:3]*delta
    logs.append(error)
    if epoch in [1,2,5,10,20,40]: selected.append(dict(epoch=epoch,error=error,weights=w.copy()))
write('streetlight-backprop','SL_DATA',dict(dataset=dict(labels=['Lampu Kiri','Lampu Tengah','Lampu Kanan','Keputusan'],rows=rows,note='Data sintetis. 0=STOP, 1=WALK.'),weights0=w0,alpha=.1,singleExample=dict(input=[1,0,1],goal=0,selected=single),wholeDataset=dict(errorPerEpoch=logs,selected=selected,finalWeights=w)))

# Backpropagation: all derivatives use old weights, one atomic update.
x=np.array([1.,.5,-2.]); w=np.array([[.2,-.1,.4,0],[-.3,.5,-.2,1],[.1,.2,0,-.5]]); v=np.array([0,.5,1.,-1.]); target=.8
z=x@w;h=np.maximum(z,0);y=h@v;delta=y-target;dv=h*delta;dh=delta*v*(z>0);dw=np.outer(x,dh);wn=w-.1*dw;vn=v-.1*dv;hn=np.maximum(x@wn,0);yn=hn@vn
states=[('Nilai awal','setup',[None]*4,None,'', ['Objektif L = ½(ŷ − t)². MSE = (ŷ − t)².']),('Pra-aktivasi','forward',z,None,'z₁',[f'z = xW = {vec(z)}']),('Aktivasi ReLU','forward',h,None,'h',[f'h = max(0,z) = {vec(h)}']),('Keluaran','forward',h,y,'h',[f'ŷ = hW = {y:.4f}']),('Galat','compare',h,y,'h',[f'delta = ŷ − t = {delta:.4f}',f'L = {delta**2/2:.4f}, MSE = {delta**2:.4f}']),('Gradien bobot keluaran','backward',h,y,'h',[f'∂L/∂W₁₂ = h × delta = {vec(dv)}','Bobot belum diperbarui.']),('Gradien tersembunyi','backward',dh,y,'delta_h',[f'delta_h = delta × W₁₂ lama × ReLU′(z) = {vec(dh)}']),('Gradien masukan dan pembaruan serentak','backward',dh,y,'delta_h',[f'∂L/∂W₀₁ = outer(x,delta_h) = {vec(dw)}','W baru = W lama − 0,1 × gradien. Kedua matriks diperbarui setelah semua gradien tersedia.']),('Verifikasi','verify',hn,yn,"h'",[f'ŷ baru = {yn:.4f}',f'MSE baru = {(yn-target)**2:.6f}'])]
steps=[]
for i,(title,phase,hidden,out,sub,trace) in enumerate(states):
    steps.append(dict(title=f'{i}. {title}',phase=phase,hidden=hidden,output=out,hiddenSub=sub,W01=wn if i>=7 else w,W12=vn if i>=7 else v,W01highlight=i==7,W12highlight=i==7,trace=trace))
write('backprop-visualizer','BP_DATA',dict(x=x,target=target,alpha=.1,W01_initial=w,W12_initial=v,W01_final=wn,W12_final=vn,steps=steps,mseHistory=[delta**2,(yn-target)**2]))

# CNN cross-correlation and pooling, derived from input pixels.
c=SPEC['cnn'];im=np.array(c['image']);k=np.array(c['kernel']);fm=np.array([[np.sum(im[i:i+3,j:j+3]*k) for j in range(4)] for i in range(4)])
c['featureMap']=fm;c['pooled']=np.array([[fm[i:i+2,j:j+2].max() for j in [0,2]] for i in [0,2]])
write('cnn-basics','CNN_DATA',c)

def iou(a,b):
    inter=max(0,min(a[2],b[2])-max(a[0],b[0]))*max(0,min(a[3],b[3])-max(a[1],b[1]))
    union=(a[2]-a[0])*(a[3]-a[1])+(b[2]-b[0])*(b[3]-b[1])-inter
    return inter/union if union>0 else 0.
od=SPEC['detection']
for p in od['iou']['presets']:p['iou']=iou(od['iou']['groundTruth'],p['box'])
pending=sorted(od['nms']['boxes'],key=lambda b:-b['score']);keep=[];trace=[]
while pending:
    best=pending.pop(0);keep.append(best['id']);trace.append(f"Pertahankan Box {best['id']} dengan skor {best['score']}.")
    rest=[]
    for b in pending:
        score=iou(best['box'],b['box']);drop=score>=od['nms']['iouThreshold'];trace.append(f"IoU({best['id']},{b['id']})={score:.4f}: "+('hapus' if drop else 'pertahankan sebagai kandidat'))
        if not drop:rest.append(b)
    pending=rest
od['nms']['keep']=keep;od['nms']['steps']=trace
write('object-detection','OD_DATA',od)

# Nonlinearity: actual fitted classifiers, seed fixed.
X,y=make_circles(n_samples=200,factor=.4,noise=.06,random_state=7)
lin=LogisticRegression().fit(X,y);nn=MLPClassifier(hidden_layer_sizes=(8,),activation='relu',solver='lbfgs',max_iter=2000,random_state=7).fit(X,y)
axis=np.linspace(-1.5,1.5,30);grid=np.array([[a,b] for b in axis for a in axis])
dn=dict(acc_lin=lin.score(X,y),acc_nn=nn.score(X,y),grid_res=30,grid_range=[-1.5,1.5],Zlin=lin.predict(grid).reshape(30,30),Znn=nn.predict(grid).reshape(30,30),X0=X[y==0],X1=X[y==1])
write('nonlinearity-activation','NL_DONUT_DATA',dn,'donut_data.js')
write('nonlinearity-activation','NL_DATA',SPEC['activation'])

# Matched dropout experiments: same data, size, initialization, batch ordering.
digits=load_digits();X=digits.data/16.;y=digits.target
idx=np.arange(len(y));train,rest=train_test_split(idx,train_size=120,stratify=y,random_state=42);val,test=train_test_split(rest,train_size=80,stratify=y[rest],random_state=42)
def train_network(seed,keep):
    rng=np.random.default_rng(seed);W=rng.normal(0,.12,(64,40));V=rng.normal(0,.12,(40,10));b=np.zeros(40);c=np.zeros(10);mask_rng=np.random.default_rng(seed+1000)
    logs=[];best_loss=float('inf');best=None;stopped=None
    for epoch in range(1,301):
        for batch in np.array_split(rng.permutation(train),15):
            xb=X[batch];t=np.eye(10)[y[batch]];h=np.maximum(xb@W+b,0);mask=(mask_rng.random(h.shape)<keep)/keep if keep<1 else np.ones_like(h);hd=h*mask;o=hd@V+c;do=(o-t)/(len(batch)*10);dh=(do@V.T)*mask*(h>0)
            W-=.5*xb.T@dh;b-=.5*dh.sum(0);V-=.5*hd.T@do;c-=.5*do.sum(0)
        row={'epoch':epoch}
        # Test is evaluated only for the selected/final models, never per epoch.
        for key,ix in [('train',train),('val',val)]:
            out=np.maximum(X[ix]@W+b,0)@V+c;row[key+'_loss']=float(np.mean((out-np.eye(10)[y[ix]])**2));row[key+'_acc']=float(np.mean(out.argmax(1)==y[ix]))
        logs.append(row)
        if stopped is None:
            if row['val_loss']<best_loss:
                best_loss=row['val_loss'];best=(epoch,W.copy(),V.copy(),b.copy(),c.copy(),row.copy())
            elif epoch-best[0]>=15:stopped=epoch
    ep,bw,bv,bb,bc,br=best
    final_test=float(np.mean((np.maximum(X[test]@W+b,0)@V+c).argmax(1)==y[test]));best_test=float(np.mean((np.maximum(X[test]@bw+bb,0)@bv+bc).argmax(1)==y[test]))
    meta=dict(stoppedAt=stopped or 300,bestEpoch=ep,bestValLoss=best_loss,restoredValAcc=br['val_acc'],restoredTestAcc=best_test)
    return logs,meta,dict(train_acc=logs[-1]['train_acc'],val_acc=logs[-1]['val_acc'],test_acc=final_test)
base,meta,bfinal=train_network(42,1);drop,_,dfinal=train_network(42,.5)
rep=[]
for seed in [42,43,44]:
    if seed==42:a,b=bfinal,dfinal
    else:_,_,a=train_network(seed,1);_,_,b=train_network(seed,.5)
    rep.append(dict(seed=seed,baseline=a['test_acc'],dropout=b['test_acc']))
write('regularization','REG_DATA',dict(baseline=base,dropout=drop,earlyStop=base[:meta['stoppedAt']],earlyStopMeta=meta,baselineFinal=bfinal,dropoutFinal=dfinal,repeats=rep,setup=dict(n_train=len(train),n_val=len(val),n_test=len(test),hidden=40,epochs=300,learning_rate=.5,batch_size=8,seeds=[42,43,44],objective='half mean squared error')))
print('Generated all 9 advanced ML topics')
