"""Per-topic learning design and traceable primary references."""
SK='https://scikit-learn.org/stable/modules/'
PT='https://docs.pytorch.org/docs/stable/'
# path: prerequisite, duration, provenance, interpretation, predict, transfer, reference
LESSONS = {
'ml/pandas':('Tabel dan indeks',20,'Simulasi operasi pada data gudang kecil. Tidak menjalankan Python di peramban.','Pengisian nol pada kolom turunan adalah keputusan eksplisit. dropna menghapus baris, sedangkan isnull hanya menandainya.','Apa hasil penjumlahan sebelum nilai kosong diisi?','Bandingkan membuang baris dengan imputasi pada data yang sama.','https://pandas.pydata.org/docs/user_guide/missing_data.html'),
'ml/linear-regression':('Persamaan garis dan rata-rata',25,'Regresi dilatih pada bensin.csv dan MLG_data.csv.','R² uji dapat turun saat fitur ditambah. Residual adalah nilai aktual dikurangi prediksi. Korelasi tidak membuktikan sebab-akibat.','Bagaimana garis berubah bila satu pengamatan jauh dari pola umum?','Bandingkan residual pada rentang liter rendah dan tinggi.',SK+'linear_model.html#ordinary-least-squares'),
'ml/logistic-regression':('Fungsi sigmoid dan probabilitas',25,'Model dilatih pada dua kelas Iris. Penanda uji mengikuti indeks baris asli.','Ambang mengubah label keputusan, bukan probabilitas model. Hasil pada dua kelas yang mudah dipisahkan tidak berlaku untuk semua data.','Apa yang terjadi pada recall saat ambang diturunkan?','Jelaskan pilihan ambang untuk deteksi penyakit dan deteksi spam.',SK+'linear_model.html#logistic-regression'),
'ml/decision-tree':('Probabilitas kelas',25,'Contoh 15 baris dan model pada decisiontree_ch6.csv memakai data berbeda.','Entropi maksimum log₂ K untuk K kelas. Akurasi uji dengan sampel kecil dapat berubah besar bila satu prediksi berubah.','Fitur mana yang memberi penurunan entropi terbesar?','Buat satu contoh ketika pohon terlalu dalam menghafal data.',SK+'tree.html'),
'ml/random-forest':('Pohon keputusan',30,'Tujuh pohon bagging ilustratif dan Random Forest 100 pohon merupakan dua model terpisah.','Pada Random Forest, kandidat fitur dipilih per pemisahan. Importance berbasis impurity bukan frekuensi fitur atau pengaruh kausal.','Apakah tujuh pohon selalu menghasilkan prediksi lebih baik?','Bandingkan suara mayoritas dan rata-rata probabilitas.',SK+'ensemble.html#random-forests-and-other-randomized-tree-ensembles'),
'ml/naive-bayes':('Probabilitas bersyarat',30,'Contoh email sintetis dan Titanic berlabel dengan pembagian berstrata 80/20, benih 42.','Independensi yang diasumsikan bersyarat pada kelas. GaussianNB adalah baseline sederhana untuk fitur campuran.','Apa yang terjadi jika likelihood satu fitur nol?','Bandingkan GaussianNB dengan model yang menangani fitur kategorikal.',SK+'naive_bayes.html'),
'ml/churn-prediction':('Klasifikasi dan metrik evaluasi',35,'Dataset churn contoh kuliah. AUC memakai probabilitas, pembagian berstrata, dan validasi silang pada data latih.','Pilih metrik berdasarkan biaya keputusan. Pentingnya fitur bukan hubungan sebab-akibat.','Model mana yang lebih sesuai bila pelanggan churn terlewat sangat mahal?','Rancang evaluasi dengan anggaran promosi retensi terbatas.',SK+'model_evaluation.html#roc-metrics'),
'ml/clustering':('Jarak Euclidean dan standardisasi',25,'K-Means dilatih pada durasi dan jarak penerbangan yang distandardisasi.','Siku SSE adalah petunjuk. Validasi kelompok dengan konteks dan kestabilan, bukan label benar-salah yang tidak tersedia.','Apa akibat memakai jarak km tanpa standardisasi?','Bandingkan K=2 dan K=4 dari ukuran kelompok serta interpretasi.',SK+'clustering.html#k-means'),
'ml/market-basket':('Frekuensi dan probabilitas',25,'Aturan dihitung dari transaksi kedai kopi menggunakan Apriori.','Lift bukan jumlah transaksi. Hubungan langka dapat memiliki lift tinggi. Asosiasi tidak membuktikan pembelian satu produk menyebabkan pembelian lain.','Bisakah produk populer memiliki confidence tinggi tetapi lift mendekati 1?','Buat aturan dengan confidence tinggi dan lift rendah.','https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/'),
'ml-lanjut/forward-propagation':('Vektor dan perkalian matriks',25,'Bobot dan input contoh manual, keluaran dihitung ulang oleh generator.','Di halaman ini W berbentuk output×input. Bias dan aktivasi dihilangkan untuk isolasi operasi linear. Pada jaringan umum, gunakan aktivasi(Wx+b).','Berapa bentuk matriks untuk tiga input dan dua output?','Tambahkan bias lalu hitung ulang satu prediksi.','https://numpy.org/doc/stable/reference/generated/numpy.matmul.html'),
'ml-lanjut/gradient-descent':('Turunan fungsi kuadrat',25,'Simulasi numerik dengan objektif ½(ŷ−t)². MSE ditampilkan sebagai ukuran galat.','Kurva perbandingan mencatat galat setelah pembaruan. Alpha kedua metode berbeda, sehingga bukan uji kecepatan terkontrol.','Apa akibat menggandakan skala input pada besar gradien?','Tentukan alpha yang membuat pembaruan berosilasi.',PT+'generated/torch.optim.SGD.html'),
'ml-lanjut/generalizing-gd':('Outer product dan penurunan gradien',30,'Perhitungan manual pada satu sampel. Perbandingan pembekuan memakai alpha yang sama.','Bobot yang dibekukan adalah satu koneksi menuju neuron yang sama. Galat tabel dihitung sebelum pembaruan, kolom bobot menampilkan keadaan sesudahnya.','Koneksi mana yang tidak berubah ketika inputnya nol?','Hitung satu matriks gradien untuk dua input dan tiga output.',PT+'generated/torch.nn.Linear.html'),
'ml-lanjut/streetlight-backprop':('Dot product dan galat kuadrat',25,'Enam baris pola lampu sintetis untuk latihan aritmetika.','Prediksi adalah jumlah kontribusi bobot, bukan selisih. Galat online dijumlahkan selama pembaruan, bukan evaluasi satu snapshot akhir.','Mengapa bobot tengah tidak berubah jika dilatih hanya pada [1,0,1]?','Uji bobot akhir pada kombinasi lampu yang tidak ada dalam data.',PT+'generated/torch.nn.Linear.html'),
'ml-lanjut/nonlinearity-activation':('Transformasi afin dan turunan',30,'Data cincin sintetis, Logistic Regression dan jaringan ReLU 8 neuron benar-benar dilatih.','Panel delta menunjukkan gradien terhadap aktivasi h. Kalikan turunan aktivasi untuk gradien terhadap z. Akurasi yang ditampilkan adalah akurasi latih.','Apakah menambah lapisan linear tanpa aktivasi dapat memisahkan cincin?','Hitung turunan ReLU, sigmoid, dan tanh pada nilai dekat saturasi.',PT+'generated/torch.nn.ReLU.html'),
'ml-lanjut/backprop-visualizer':('Aturan rantai dan ReLU',35,'Satu jaringan manual. Semua angka dihitung ulang dari input dan bobot awal.','Objektif L=½(ŷ−t)² memiliki delta=ŷ−t. Semua gradien dihitung dari bobot lama sebelum pembaruan serentak.','Neuron mana yang gradiennya nol pada contoh ini?','Verifikasi satu gradien dengan beda hingga.',PT+'notes/autograd.html'),
'ml-lanjut/regularization':('Data latih, validasi, dan uji',35,'Digits 8×8, jaringan 64→40→10. Pembanding dropout berukuran sama, diulang pada benih 42,43,44.','Validasi memilih checkpoint. Data uji dipakai pada checkpoint terpilih dan akhir, bukan sebagai panduan setiap epoch. Hasil satu benih tidak menjamin keunggulan dropout.','Apakah galat latih yang terus turun selalu diikuti galat validasi?','Bandingkan variasi hasil tiga benih sebelum menyimpulkan efek dropout.',PT+'generated/torch.nn.Dropout.html'),
'ml-lanjut/cnn-basics':('Perkalian dan penjumlahan matriks',25,'Piksel dan kernel sintetis. Feature map dan pooling dihitung ulang.','Operasi yang lazim disebut konvolusi pada CNN adalah korelasi silang tanpa pembalikan kernel. Pooling membuang informasi selain maksimum lokal.','Berapa ukuran keluaran 6×6 dengan kernel 3×3, stride 1, tanpa padding?','Balik tanda kernel dan hitung respons tepinya.',PT+'generated/torch.nn.Conv2d.html'),
'ml-lanjut/object-detection':('Luas persegi panjang dan probabilitas',30,'Kotak ilustratif dengan IoU dan NMS yang dihitung dari koordinat.','Grid dan anchor adalah penyederhanaan keluarga YOLO berbasis anchor, bukan semua versi YOLO. Normalisasi ukuran kotak harus menyebut acuannya. NMS contoh ini satu kelas.','Apakah dua kotak dengan IoU tinggi selalu mewakili objek yang sama?','Jelaskan mengapa evaluasi deteksi memerlukan kelas dan pencocokan unik.','https://arxiv.org/abs/1612.08242'),
'nlp/word-embeddings':('Vektor, sudut, dan dot product',25,'Vektor semantik manual 10 dimensi, diproyeksikan dengan PCA. Bukan hasil pelatihan embedding.','Dimensi berlabel merupakan rancangan ilustrasi. Tidak ada ambang cosine universal. Analogi dan stereotip dalam nilai manual tidak menjadi fakta bahasa atau sosial.','Apakah jarak dekat pada PCA selalu berarti cosine tinggi pada ruang asal?','Cari analogi yang gagal dan jelaskan batas contoh ini.','https://arxiv.org/abs/1301.3781'),
'nlp/rnn':('Perkalian matriks dan tanh',30,'Forward pass memakai bobot manual. Gradien dihitung pada jaringan skalar dengan parameter tetap.','RNN melibatkan turunan aktivasi. LSTM membandingkan jalur cell state dengan gerbang konstan, bukan jaringan terlatih penuh.','Bagaimana perubahan urutan kata memengaruhi hidden state?','Ubah bobot rekuren dan telusuri hasil kali turunannya.',PT+'generated/torch.nn.RNN.html'),
'nlp/autograd':('Aturan rantai',25,'Graf tensor kecil dengan perhitungan gradien manual.','Dalam PyTorch, backward mengakumulasi gradien pada tensor leaf. Kosongkan gradien sebelum langkah baru bila tidak menghendaki akumulasi lintas batch.','Berapa gradien b jika b digunakan pada dua cabang?','Bandingkan dua backward dengan dan tanpa pengosongan gradien.','https://docs.pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html'),
'nlp/lstm-attention':('RNN dan sigmoid',30,'Gerbang skalar dan hidden state ilustratif dengan bobot yang dipilih manual.','LSTM memiliki tiga gerbang dan satu kandidat pembaruan sel. Gerbang tidak selalu merespons x dengan arah seperti contoh. Konteks dot-product attention berada dalam convex hull value.','Apa hasil jika forget gate mendekati 0?','Bandingkan dot-product attention dengan additive attention.',PT+'generated/torch.nn.LSTM.html'),
'nlp/self-attention':('Dot product, softmax, dan matriks',35,'Embedding manual, dua proyeksi dirancang, satu proyeksi acak.','Nama kepala bukan fungsi linguistik yang terbukti. Self-attention memerlukan informasi posisi untuk menyandikan urutan. Kompleksitas kuadratik berlaku untuk full attention.','Apa akibat menaikkan semua skor QK dengan faktor positif besar?','Tukar urutan token tanpa positional encoding dan amati permutasinya.','https://arxiv.org/abs/1706.03762'),
'nlp/transformer':('Self-attention dan jaringan saraf',35,'Diagram arsitektur encoder-decoder klasik. Angka dan teks demonstrasi bersifat ilustratif.','BERT encoder-only, GPT decoder-only tanpa cross-attention encoder, T5 encoder-decoder. Pelatihan paralel berbeda dari generasi autoregresif.','Dari mana Q, K, V pada cross-attention berasal?','Telusuri satu token keluaran beserta mask dan sambungan residual.','https://arxiv.org/abs/1706.03762'),
'nlp/text-classification':('Representasi teks dan klasifikasi',30,'Batas keputusan, skor, dan confusion matrix dirancang sebagai ilustrasi, bukan pelatihan IndoBERT.','Pipeline klasik dapat memakai TF-IDF. BERT memakai tokenizer checkpoint, attention mask, dan token khusus. Jangan otomatis membuang negasi atau stopword sebelum BERT.','Apa dampak menghapus kata tidak pada analisis sentimen?','Hitung precision dan recall dari confusion matrix ilustratif.','https://huggingface.co/docs/transformers/tasks/sequence_classification'),
'nlp/ner':('Tokenisasi dan klasifikasi',30,'Contoh IOB2 dan evaluator JavaScript ilustratif. Angka model diwarisi dari materi sumber, bukan eksperimen baru.','Pelabelan hanya subkata pertama adalah pilihan pelatihan. Evaluator panel memakai aturan permisif seperti seqeval default, bukan strict IOB2. Entitas cocok bila tipe dan rentang sama.','Apa dampak B-PER berubah menjadi I-PER pada awal urutan?','Bandingkan token accuracy dengan entity F1.','https://github.com/chakki-works/seqeval'),
'nlp/summarization':('Generasi teks dan n-gram',30,'Keluaran contoh tersimpan dari materi kuliah. Belum menjadi benchmark lintas dataset.','Satu artikel dan checkpoint berbeda tidak cukup untuk memeringkat model. BLEU panel adalah sentence BLEU-4 dengan tokenizer spasi dan add-one opsional. ROUGE menampilkan P/R/F1.','Bisakah sinonim menurunkan skor tanpa menurunkan kualitas makna?','Nilai faktualitas ringkasan secara terpisah dari kemiripan n-gram.','https://aclanthology.org/P02-1040/'),
'nlp/question-answering':('Tokenisasi dan Transformer',30,'Skor span manual, contoh jawaban tersimpan, serta ilustrasi sliding window dan RAG.','Span harus berada pada konteks, awal≤akhir, dan memenuhi batas panjang. Argmax independen tidak menjamin span sah. RAG tidak menjamin jawaban benar.','Apa yang terjadi bila start tertinggi berada setelah end tertinggi?','Rancang kasus konteks tidak memiliki jawaban dan bukti yang dibutuhkan.','https://huggingface.co/docs/transformers/tasks/question_answering'),
'kecerdasan-komputasional/pemodelan-pencarian':('Graf dan keadaan',35,'Graf kecil dan algoritma pencarian diimplementasikan langsung dalam Python.','BFS minimum ruas, UCS minimum biaya nonnegatif. Greedy tidak menjamin biaya optimal. Hitungan kunjungan berarti node dikeluarkan dan diproses.','Apakah jalur tiga ruas selalu lebih murah dari empat ruas?','Ubah satu bobot ruas dan bandingkan BFS dengan UCS.','https://aima.cs.berkeley.edu/'),
'kecerdasan-komputasional/teknik-pemecahan':('Graf, logika, dan batasan',40,'Graf AND-OR, pewarnaan, SEND+MORE, dan aturan keluarga ditetapkan dalam kode.','Simpul pengelompokan AND bukan aksi tambahan. Biaya dihitung pada ruas aksi asli. Rujukan nomor buku lama belum diverifikasi terhadap edisi dan halaman.','Mengapa carry terakhir SEND+MORE harus 1?','Turunkan O=0 dari kolom ribuan dan keunikan digit, lalu jelaskan pengurangan kandidat.','https://aima.cs.berkeley.edu/'),
'kecerdasan-komputasional/penalaran-ketidakpastian':('Probabilitas bersyarat dan himpunan',35,'Probabilitas dan massa kepercayaan merupakan contoh pedagogis, bukan data diagnosis klinis.','Probabilitas, faktor kepastian, dan massa Dempster-Shafer memiliki makna berbeda. Massa pada himpunan bukan probabilitas satu anggota. Konflik total membuat normalisasi tidak terdefinisi.','Mengapa posterior harus dinormalisasi?','Bandingkan konflik tinggi dengan bukti yang benar-benar tidak informatif.','https://aima.cs.berkeley.edu/'),
'kecerdasan-komputasional/jaringan-syaraf-tiruan':('Vektor dan fungsi aktivasi',40,'Perceptron, jaringan huruf sintetis, pembelajaran kompetitif tanpa label, dan SOM.','Contoh prototipe tanpa label bukan LVQ terawasi. Jarak yang dipakai L1. Akurasi huruf dihitung pada data latih dan tidak mengukur generalisasi.','Mengapa bobot prototipe menjadi kontinu setelah pembaruan?','Bandingkan pembaruan prototipe tanpa label dengan LVQ berlabel.',PT+'generated/torch.nn.Linear.html'),
'kecerdasan-komputasional/algoritma-genetika':('Biner, probabilitas, dan optimasi',35,'Kromosom 18 bit dan fungsi sinus sintetis. Enam pengulangan per kombinasi parameter.','Generasi pertama dapat sudah memenuhi target. Bandingkan jumlah evaluasi fitness serta variasi, bukan generasi saja. Bedakan terbaik saat ini dan terbaik sepanjang proses.','Mengapa populasi besar mungkin lebih cepat dalam generasi namun lebih mahal?','Bandingkan keberhasilan beberapa benih pada batas evaluasi yang sama.','https://deap.readthedocs.io/en/master/tutorials/basic/part2.html'),
'kecerdasan-komputasional/kecerdasan-kawanan-fuzzy':('Probabilitas, optimasi, dan himpunan',40,'Contoh ACO, varian ABC maksimisasi, dan fungsi keanggotaan manual.','ABC memaksimumkan fungsi pada domain terbatas. Tsukamoto dan Mamdani berbeda dalam konsekuen dan inferensi. Kelayakan satu hasil tidak membuktikan keunggulan umum metode.','Apa akibat bobot feromon awal sama tetapi panjang jalur berbeda?','Uji batas stok sebagai syarat kelayakan terpisah dari defuzzifikasi.','https://www.scholarpedia.org/article/Ant_colony_optimization'),
}

# path: (eksplorasi, perhitungan) yang merujuk kontrol dan hasil pada halaman itu
STEPS = {
'ml/pandas':('Klik Selection, Slicing, .loc, .iloc, lalu Filtering secara berurutan dan catat baris serta kolom mana yang ikut terpilih.','Pada tab Data Kosong dan Binning, jalankan dropna() dan Kolom Turunan + Binning, lalu hitung sendiri jumlah baris yang tersisa dan kelompok bin satu baris.'),
'ml/linear-regression':('Geser slider prediksi pada Regresi Sederhana, lalu di tab kedua bandingkan model 1 fitur, 2 fitur, dan 4 fitur.','Ambil satu nilai liter, hitung prediksi dengan persamaan garis yang ditampilkan, lalu hitung residualnya dari nilai aktual.'),
'ml/logistic-regression':('Geser slider panjang sepal dan lebar sepal, lalu amati kapan titik berpindah sisi decision boundary.','Pada tab Fungsi Sigmoid, hitung σ(z)=1/(1+e^(−z)) untuk satu nilai z dan cocokkan dengan kurva.'),
'ml/decision-tree':('Klik ketiga kandidat pemisah (Mesin Bensin?, Penggerak Depan?, Bangku > 5?) dan bandingkan entropi anak yang dihasilkan.','Hitung information gain satu pemisah: entropi induk dikurangi rata-rata tertimbang entropi anak, lalu cocokkan dengan angka pada panel.'),
'ml/random-forest':('Ganti baris data uji pada tab Ensemble Voting dan catat pohon mana yang berubah suara.','Hitung suara mayoritas dari tujuh pohon untuk satu baris uji, lalu bandingkan dengan prediksi akhir yang ditampilkan.'),
'ml/naive-bayes':('Ubah pilihan Diskon dan Hadiah, lalu aktifkan dan nonaktifkan Laplace Smoothing.','Kalikan prior dengan setiap likelihood untuk satu kelas, lalu normalisasikan kedua skor dan cocokkan dengan posterior di panel.'),
'ml/churn-prediction':('Bandingkan model pada tab Perbandingan Model, lalu geser jumlah kasus pada tab Evaluasi Agregat.','Dari confusion matrix satu model, hitung precision dan recall kelas churn secara manual.'),
'ml/clustering':('Klik K = 2 sampai 5 dan amati bentuk kelompok serta posisi titik pada kurva siku SSE.','Pilih satu rute pada tab Detail Cluster dan jelaskan mengapa rute itu masuk ke centroid terdekatnya.'),
'ml/market-basket':('Ganti produk pada tab Jelajahi Produk dan bandingkan aturan yang muncul.','Untuk satu aturan A→B, hitung support, confidence = support(A∪B)/support(A), dan lift = confidence/support(B).'),
'ml-lanjut/forward-propagation':('Klik skenario Input Tunggal sampai Jaringan 2 Lapis dan amati bentuk matriks bobot pada tiap skenario.','Hitung satu keluaran sebagai dot product baris bobot dengan vektor input, lalu cocokkan dengan hasil NumPy.'),
'ml-lanjut/gradient-descent':('Coba preset Normal, Broken, dan Fixed, lalu geser slider input dan alpha sendiri.','Pada tab Satu Iterasi GD, hitung delta = prediksi − target, weight_delta = delta × input, dan bobot baru = bobot − alpha × weight_delta.'),
'ml-lanjut/generalizing-gd':('Bandingkan mode Normal dengan Bekukan weight[0] (toes) dan amati bobot mana yang tetap.','Pada Update Bobot Satu Langkah, hitung satu elemen gradien sebagai input × delta, lalu kurangi alpha kali nilai itu dari bobot lama.'),
'ml-lanjut/streetlight-backprop':('Bandingkan tab Belajar dari Satu Contoh dengan Belajar dari Seluruh Dataset, terutama bobot lampu tengah.','Hitung prediksi satu pola lampu sebagai jumlah input × bobot, lalu hitung galat kuadratnya terhadap target.'),
'ml-lanjut/nonlinearity-activation':('Geser slider δ(2) pada tab Delta Propagation, lalu bandingkan batas keputusan linear dan non-linear.','Hitung δ(1) satu node sebagai δ(2) × bobot, lalu cocokkan dengan jejak perhitungan di bawah grafik.'),
'ml-lanjut/backprop-visualizer':('Telusuri tombol Sebelumnya dan Selanjutnya dari forward pass sampai pembaruan bobot.','Hitung satu gradien bobot dengan aturan rantai (delta × turunan ReLU × input), lalu cocokkan dengan angka pada langkah itu.'),
'ml-lanjut/regularization':('Bandingkan kurva pada tab Overfitting, Early Stopping, dan Dropout, lalu klik Acak Ulang Mask.','Baca epoch checkpoint terpilih pada Early Stopping dan jelaskan mengapa galat validasi, bukan galat uji, yang menentukannya.'),
'ml-lanjut/cnn-basics':('Geser posisi kernel dan amati sel feature map yang ikut berubah.','Hitung satu nilai feature map sebagai jumlah perkalian elemen patch 3×3 dengan kernel, lalu hitung max pooling dari blok 2×2.'),
'ml-lanjut/object-detection':('Geser kotak prediksi secara horizontal, vertikal, dan skala, lalu bandingkan Sebelum NMS dan Sesudah NMS.','Hitung IoU = luas irisan / luas gabungan dari koordinat kedua kotak dan cocokkan dengan nilai di panel.'),
'nlp/word-embeddings':('Pilih kata A, B, dan C pada tab Analogi Kata, lalu ganti Kata 1 dan Kata 2 pada tab Cosine Similarity.','Hitung cosine similarity dua vektor sebagai dot product dibagi hasil kali panjang keduanya.'),
'nlp/rnn':('Ganti kalimat pada Forward Pass, lalu geser panjang sequence pada tab Vanishing Gradient.','Hitung satu hidden state h_t = tanh(W_x x_t + W_h h_(t−1)) untuk satu dimensi dan cocokkan dengan angka pada langkah itu.'),
'nlp/autograd':('Bandingkan Autograd Naif (Ada Bug) dengan Autograd Diperbaiki, lalu coba preset g=0.9, 1.0, dan 1.1.','Hitung g pangkat n untuk satu preset dan jelaskan kaitannya dengan gradien yang menghilang atau meledak.'),
'nlp/lstm-attention':('Geser input x_t pada tab LSTM vs GRU, lalu geser Query x dan Query y pada Classical Attention.','Hitung bobot attention dengan softmax dari skor, lalu hitung konteks sebagai jumlah tertimbang value.'),
'nlp/self-attention':('Ganti kalimat pada tiap tab dan telusuri langkah Query-Key-Value dengan tombol Selanjutnya.','Hitung satu baris attention: skor QKᵀ dibagi √d_k, lalu softmax, dan cocokkan dengan baris matriks.'),
'nlp/transformer':('Telusuri langkah pada tab Encoder Detail dan Decoder Detail, perhatikan kapan mask dan cross-attention dipakai.','Jelaskan asal Q, K, dan V pada cross-attention serta bentuk tensor sebelum dan sesudah sambungan residual.'),
'nlp/text-classification':('Ganti teks contoh pada Pipeline, lalu telusuri langkah BERT Fine-tuning.','Dari confusion matrix ilustratif, hitung precision, recall, dan F1 satu kelas.'),
'nlp/ner':('Klik token untuk melihat tag IOB2, lalu ubah tag prediksi pada tab Evaluasi Level-Entitas.','Hitung precision, recall, dan F1 tingkat entitas setelah satu tag diubah, lalu bandingkan dengan token accuracy.'),
'nlp/summarization':('Ganti kalimat kandidat dan referensi pada tab BLEU dan ROUGE, lalu aktifkan smoothing.','Hitung presisi unigram dan bigram yang terpotong (clipped) untuk kalimat kandidat, lalu cocokkan dengan panel BLEU.'),
'nlp/question-answering':('Pilih mode Token Awal atau Token Akhir, lalu klik token konteks untuk membentuk span jawaban.','Jumlahkan skor start dan end untuk span pilihan Anda, lalu periksa apakah span itu sah (awal ≤ akhir dan di dalam konteks).'),
'kecerdasan-komputasional/pemodelan-pencarian':('Bandingkan BFS, DFS, Greedy Best First, dan Uniform Cost Search pada peta, lalu Min-max Murni dengan Alpha-Beta Pruning.','Jumlahkan biaya ruas jalur UCS secara manual dan telusuri satu pemangkasan alpha-beta beserta nilai alpha dan beta-nya.'),
'kecerdasan-komputasional/teknik-pemecahan':('Buka tab Problem Reduction, Pewarnaan Peta, Kriptaritmatika, Penalaran Batasan, dan Logic Programming secara berurutan.','Pada Problem Reduction, hitung biaya minimum dari akar dengan menjumlahkan biaya ruas simpul AND dan memilih minimum simpul OR.'),
'kecerdasan-komputasional/penalaran-ketidakpastian':('Bandingkan Dua Gejala dengan Tiga Gejala pada tab Dempster-Shafer, lalu buka Faktor Kepastian dan Vector Space Model.','Hitung satu sel Tabel Kombinasi (m1 × m2) dan normalisasikan dengan 1 − konflik.'),
'kecerdasan-komputasional/jaringan-syaraf-tiruan':('Bandingkan Aturan Perceptron: AND & OR dengan Back Propagation: Kenali Huruf, lalu buka tab Kohonen Network.','Hitung satu pembaruan perceptron w_baru = w + α(target − y)x untuk satu contoh input.'),
'kecerdasan-komputasional/algoritma-genetika':('Buka tab dari Penyandian Kromosom sampai Eksperimen Parameter dan perhatikan perubahan fitness terbaik tiap generasi.','Dekodekan satu kromosom biner menjadi nilai x, hitung fitness-nya, lalu hitung peluang terpilihnya pada roulette wheel.'),
'kecerdasan-komputasional/kecerdasan-kawanan-fuzzy':('Bandingkan Metode Tsukamoto dan Metode Mamdani pada tab Sistem Fuzzy, lalu amati feromon ACO setelah kedua semut lewat.','Hitung derajat keanggotaan satu nilai pada fungsi segitiga, lalu terapkan operator MIN untuk satu aturan.'),
}

# Supplementary labs share the same metadata and learning-aid pipeline.
from new_lessons import NEW
for slug, lesson in NEW.items():
    LESSONS[slug]=(lesson['prereq'],25,'Simulasi sintetis deterministik; tidak menjalankan model pretrained.',lesson['note'],'Prediksi perubahan keluaran sebelum mengubah satu kontrol.','Jelaskan kapan hasil eksperimen kecil ini tidak berlaku pada data nyata.',lesson['source'])
    STEPS[slug]=('Ubah satu kontrol, amati hasil tabel, lalu reset untuk membandingkan.','Hitung satu baris hasil secara manual dan bandingkan dengan penjelasan algoritma.')
