// Generated by scripts/generate_advanced.py. Seed 42 unless specified.
var OD_DATA = {
  "iou": {
    "canvasW": 500,
    "canvasH": 350,
    "groundTruth": [
      60,
      50,
      420,
      300
    ],
    "presets": [
      {
        "label": "Prediksi Bagus",
        "box": [
          80,
          60,
          440,
          310
        ],
        "iou": 0.82926829
      },
      {
        "label": "Prediksi Kurang Baik",
        "box": [
          200,
          120,
          480,
          340
        ],
        "iou": 0.35357143
      },
      {
        "label": "Tidak Ada Overlap",
        "box": [
          430,
          0,
          500,
          40
        ],
        "iou": 0.0
      }
    ]
  },
  "nms": {
    "canvasW": 600,
    "canvasH": 400,
    "boxes": [
      {
        "id": 0,
        "box": [
          80,
          60,
          380,
          300
        ],
        "score": 0.92,
        "label": "Mobil 1a"
      },
      {
        "id": 1,
        "box": [
          100,
          70,
          400,
          310
        ],
        "score": 0.85,
        "label": "Mobil 1b"
      },
      {
        "id": 2,
        "box": [
          90,
          50,
          390,
          290
        ],
        "score": 0.78,
        "label": "Mobil 1c"
      },
      {
        "id": 3,
        "box": [
          60,
          80,
          360,
          320
        ],
        "score": 0.7,
        "label": "Mobil 1d"
      },
      {
        "id": 4,
        "box": [
          400,
          200,
          570,
          370
        ],
        "score": 0.88,
        "label": "Mobil 2"
      }
    ],
    "iouThreshold": 0.5,
    "keep": [
      0,
      4
    ],
    "steps": [
      "Pertahankan Box 0 dengan skor 0.92.",
      "IoU(0,4)=0.0000: pertahankan sebagai kandidat",
      "IoU(0,1)=0.8090: hapus",
      "IoU(0,2)=0.8629: hapus",
      "IoU(0,3)=0.7476: hapus",
      "Pertahankan Box 4 dengan skor 0.88."
    ]
  },
  "yolo": {
    "gridSize": 3,
    "numClasses": 3,
    "outputPerCell": 8,
    "anchorExample": {
      "numAnchors": 2,
      "outputPerCellWithAnchors": 16
    }
  }
};
