// Generated by scripts/generate_advanced.py. Seed 42 unless specified.
var FORWARD_PROP_DATA = {
  "scenarios": [
    {
      "id": "single",
      "label": "Input Tunggal",
      "title": "Prediksi dengan Satu Input, Satu Bobot",
      "story": "Jaringan paling sederhana: satu angka masuk, dikalikan satu bobot, menghasilkan satu prediksi.",
      "layers": [
        {
          "name": "Input",
          "nodes": [
            {
              "label": "toes",
              "value": 8.5
            }
          ]
        },
        {
          "name": "Output",
          "nodes": [
            {
              "label": "menang?",
              "value": 0.85
            }
          ]
        }
      ],
      "weights": [
        [
          [
            0.1
          ]
        ]
      ],
      "trace": [
        "[[0.1]] × [8.5] = [0.85]"
      ]
    },
    {
      "id": "multi_input",
      "label": "Banyak Input",
      "title": "Prediksi dengan Banyak Input, Satu Output",
      "story": "Tiga fitur pertandingan (toes, win-loss ratio, jumlah fans) digabung lewat weighted sum untuk memprediksi menang/kalah.",
      "layers": [
        {
          "name": "Input",
          "nodes": [
            {
              "label": "toes",
              "value": 8.5
            },
            {
              "label": "wlrec",
              "value": 0.65
            },
            {
              "label": "nfans",
              "value": 1.2
            }
          ]
        },
        {
          "name": "Output",
          "nodes": [
            {
              "label": "menang?",
              "value": 0.98
            }
          ]
        }
      ],
      "weights": [
        [
          [
            0.1,
            0.2,
            0
          ]
        ]
      ],
      "trace": [
        "[[0.1, 0.2, 0]] × [8.5, 0.65, 1.2] = [0.98]"
      ]
    },
    {
      "id": "multi_output",
      "label": "Banyak Output",
      "title": "Prediksi dengan Satu Input, Banyak Output",
      "story": "Satu fitur (win-loss ratio) dipakai untuk memprediksi tiga hal sekaligus: apakah pemain cedera, menang, atau sedih &mdash; lewat elementwise multiply.",
      "layers": [
        {
          "name": "Input",
          "nodes": [
            {
              "label": "wlrec",
              "value": 0.65
            }
          ]
        },
        {
          "name": "Output",
          "nodes": [
            {
              "label": "hurt?",
              "value": 0.195
            },
            {
              "label": "win?",
              "value": 0.13
            },
            {
              "label": "sad?",
              "value": 0.585
            }
          ]
        }
      ],
      "weights": [
        [
          [
            0.3
          ],
          [
            0.2
          ],
          [
            0.9
          ]
        ]
      ],
      "trace": [
        "[[0.3], [0.2], [0.9]] × [0.65] = [0.195, 0.13, 0.585]"
      ]
    },
    {
      "id": "multi_in_out",
      "label": "Banyak Input & Output",
      "title": "Prediksi dengan Banyak Input dan Banyak Output",
      "story": "Tiga input dan tiga output dihubungkan lewat matriks bobot 3&times;3 menggunakan vect_mat_mul &mdash; setiap output adalah dot product input dengan satu baris matriks.",
      "layers": [
        {
          "name": "Input",
          "nodes": [
            {
              "label": "toes",
              "value": 8.5
            },
            {
              "label": "wlrec",
              "value": 0.65
            },
            {
              "label": "nfans",
              "value": 1.2
            }
          ]
        },
        {
          "name": "Output",
          "nodes": [
            {
              "label": "hurt?",
              "value": 0.555
            },
            {
              "label": "win?",
              "value": 0.98
            },
            {
              "label": "sad?",
              "value": 0.965
            }
          ]
        }
      ],
      "weights": [
        [
          [
            0.1,
            0.1,
            -0.3
          ],
          [
            0.1,
            0.2,
            0
          ],
          [
            0,
            1.3,
            0.1
          ]
        ]
      ],
      "trace": [
        "[[0.1, 0.1, -0.3], [0.1, 0.2, 0], [0, 1.3, 0.1]] × [8.5, 0.65, 1.2] = [0.555, 0.98, 0.965]"
      ]
    },
    {
      "id": "hidden",
      "label": "Jaringan 2 Lapis (Hidden Layer)",
      "title": "Jaringan dengan Hidden Layer",
      "story": "Input diteruskan ke hidden layer (ih_wgt) lebih dulu, baru hidden layer diteruskan ke output (hp_wgt). Inilah cikal-bakal deep network.",
      "layers": [
        {
          "name": "Input",
          "nodes": [
            {
              "label": "toes",
              "value": 8.5
            },
            {
              "label": "wlrec",
              "value": 0.65
            },
            {
              "label": "nfans",
              "value": 1.2
            }
          ]
        },
        {
          "name": "Hidden",
          "nodes": [
            {
              "label": "h0",
              "value": 0.86
            },
            {
              "label": "h1",
              "value": 0.295
            },
            {
              "label": "h2",
              "value": 1.23
            }
          ]
        },
        {
          "name": "Output",
          "nodes": [
            {
              "label": "hurt?",
              "value": 0.2135
            },
            {
              "label": "win?",
              "value": 0.145
            },
            {
              "label": "sad?",
              "value": 0.5065
            }
          ]
        }
      ],
      "weights": [
        [
          [
            0.1,
            0.2,
            -0.1
          ],
          [
            -0.1,
            0.1,
            0.9
          ],
          [
            0.1,
            0.4,
            0.1
          ]
        ],
        [
          [
            0.3,
            1.1,
            -0.3
          ],
          [
            0.1,
            0.2,
            0
          ],
          [
            0,
            1.3,
            0.1
          ]
        ]
      ],
      "trace": [
        "[[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]] × [8.5, 0.65, 1.2] = [0.86, 0.295, 1.23]",
        "[[0.3, 1.1, -0.3], [0.1, 0.2, 0], [0, 1.3, 0.1]] × [0.86, 0.295, 1.23] = [0.2135, 0.145, 0.5065]"
      ]
    }
  ],
  "numpyDemo": {
    "good": {
      "code": "a = np.array([1,2,3])\nb = np.array([0.1,0.2,0.3])\na.dot(b)",
      "result": "1.4",
      "note": "Dot product berhasil karena kedua vektor berukuran sama (3,)."
    },
    "bad": {
      "code": "a = np.array([1,2,3,4])\nb = np.array([0.1,0.2,0.3])\na.dot(b)",
      "result": "ValueError: shapes (4,) and (3,) not aligned:\n4 (dim 0) != 3 (dim 0)",
      "note": "Dot product gagal karena ukuran vektor tidak cocok (4 vs 3) — kesalahan paling umum saat membangun forward propagation manual."
    }
  }
};
