// Auto-generated by generate_clustering_data.py
// Clustering data for KupasAI ML Week 10 - real jadwal_penerbangan.csv (41 rute domestik)

const CLUSTER_DATA = {
  "n_flights": 41,
  "elbow": [
    {
      "k": 1,
      "sse": 82.0
    },
    {
      "k": 2,
      "sse": 48.16
    },
    {
      "k": 3,
      "sse": 25.04
    },
    {
      "k": 4,
      "sse": 17.51
    },
    {
      "k": 5,
      "sse": 13.61
    },
    {
      "k": 6,
      "sse": 11.24
    },
    {
      "k": 7,
      "sse": 9.28
    },
    {
      "k": 8,
      "sse": 8.0
    },
    {
      "k": 9,
      "sse": 6.14
    }
  ],
  "clusterings": {
    "2": {
      "labels": [
        0,
        0,
        0,
        0,
        1,
        0,
        1,
        0,
        0,
        1,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        0,
        0,
        1,
        1,
        1,
        0,
        0,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        0,
        0,
        1,
        1,
        1,
        0
      ],
      "centroids": [
        {
          "durasi": 111.59,
          "jarak": 984.94,
          "n": 17
        },
        {
          "durasi": 258.0,
          "jarak": 1224.38,
          "n": 24
        }
      ]
    },
    "3": {
      "labels": [
        2,
        2,
        2,
        2,
        1,
        2,
        0,
        0,
        2,
        1,
        2,
        0,
        1,
        1,
        1,
        0,
        1,
        2,
        1,
        0,
        2,
        2,
        1,
        1,
        1,
        2,
        2,
        1,
        0,
        0,
        0,
        1,
        0,
        2,
        1,
        2,
        2,
        0,
        0,
        0,
        2
      ],
      "centroids": [
        {
          "durasi": 239.5,
          "jarak": 1983.83,
          "n": 12
        },
        {
          "durasi": 264.69,
          "jarak": 619.46,
          "n": 13
        },
        {
          "durasi": 110.87,
          "jarak": 891.88,
          "n": 16
        }
      ]
    },
    "4": {
      "labels": [
        3,
        2,
        3,
        3,
        1,
        3,
        0,
        2,
        2,
        1,
        2,
        0,
        1,
        1,
        1,
        0,
        1,
        3,
        1,
        0,
        3,
        3,
        1,
        1,
        1,
        3,
        3,
        1,
        0,
        0,
        0,
        1,
        0,
        2,
        1,
        3,
        3,
        0,
        0,
        0,
        3
      ],
      "centroids": [
        {
          "durasi": 250.09,
          "jarak": 1939.27,
          "n": 11
        },
        {
          "durasi": 264.69,
          "jarak": 619.46,
          "n": 13
        },
        {
          "durasi": 96.0,
          "jarak": 1789.2,
          "n": 5
        },
        {
          "durasi": 118.08,
          "jarak": 649.83,
          "n": 12
        }
      ]
    },
    "5": {
      "labels": [
        3,
        2,
        3,
        3,
        1,
        3,
        4,
        2,
        2,
        1,
        2,
        4,
        1,
        1,
        1,
        0,
        1,
        3,
        1,
        4,
        3,
        3,
        1,
        0,
        1,
        3,
        3,
        0,
        4,
        0,
        4,
        1,
        4,
        2,
        0,
        3,
        3,
        0,
        4,
        4,
        3
      ],
      "centroids": [
        {
          "durasi": 241.67,
          "jarak": 1233.17,
          "n": 6
        },
        {
          "durasi": 268.7,
          "jarak": 485.2,
          "n": 10
        },
        {
          "durasi": 96.0,
          "jarak": 1789.2,
          "n": 5
        },
        {
          "durasi": 118.08,
          "jarak": 649.83,
          "n": 12
        },
        {
          "durasi": 256.88,
          "jarak": 2141.75,
          "n": 8
        }
      ]
    }
  },
  "flights": [
    {
      "kode": "ID7508",
      "asal": "Bandung",
      "tujuan": "Surabaya",
      "durasi": 85,
      "jarak": 662
    },
    {
      "kode": "SJ3351",
      "asal": "Makassar",
      "tujuan": "Jakarta",
      "durasi": 117,
      "jarak": 1401
    },
    {
      "kode": "GA2828",
      "asal": "Makassar",
      "tujuan": "Yogyakarta",
      "durasi": 107,
      "jarak": 1053
    },
    {
      "kode": "GA8805",
      "asal": "Bali",
      "tujuan": "Surabaya",
      "durasi": 78,
      "jarak": 306
    },
    {
      "kode": "ID8549",
      "asal": "Makassar",
      "tujuan": "Lombok",
      "durasi": 247,
      "jarak": 485
    },
    {
      "kode": "SJ1883",
      "asal": "Makassar",
      "tujuan": "Yogyakarta",
      "durasi": 151,
      "jarak": 1053
    },
    {
      "kode": "QZ6666",
      "asal": "Makassar",
      "tujuan": "Medan",
      "durasi": 278,
      "jarak": 2474
    },
    {
      "kode": "SJ6469",
      "asal": "Makassar",
      "tujuan": "Medan",
      "durasi": 123,
      "jarak": 2474
    },
    {
      "kode": "ID2303",
      "asal": "Medan",
      "tujuan": "Surabaya",
      "durasi": 94,
      "jarak": 1835
    },
    {
      "kode": "SJ6006",
      "asal": "Jakarta",
      "tujuan": "Surabaya",
      "durasi": 204,
      "jarak": 718
    },
    {
      "kode": "SJ2445",
      "asal": "Medan",
      "tujuan": "Surabaya",
      "durasi": 62,
      "jarak": 1835
    },
    {
      "kode": "GA6885",
      "asal": "Medan",
      "tujuan": "Bandung",
      "durasi": 225,
      "jarak": 2012
    },
    {
      "kode": "QZ5756",
      "asal": "Yogyakarta",
      "tujuan": "Jakarta",
      "durasi": 229,
      "jarak": 522
    },
    {
      "kode": "SJ3687",
      "asal": "Yogyakarta",
      "tujuan": "Surabaya",
      "durasi": 346,
      "jarak": 326
    },
    {
      "kode": "QZ2851",
      "asal": "Jakarta",
      "tujuan": "Surabaya",
      "durasi": 298,
      "jarak": 718
    },
    {
      "kode": "ID9607",
      "asal": "Makassar",
      "tujuan": "Jakarta",
      "durasi": 212,
      "jarak": 1401
    },
    {
      "kode": "JT9040",
      "asal": "Jakarta",
      "tujuan": "Surabaya",
      "durasi": 249,
      "jarak": 718
    },
    {
      "kode": "SJ8374",
      "asal": "Lombok",
      "tujuan": "Bandung",
      "durasi": 144,
      "jarak": 1023
    },
    {
      "kode": "ID1923",
      "asal": "Surabaya",
      "tujuan": "Lombok",
      "durasi": 255,
      "jarak": 447
    },
    {
      "kode": "QZ4368",
      "asal": "Medan",
      "tujuan": "Makassar",
      "durasi": 316,
      "jarak": 2474
    },
    {
      "kode": "SJ2719",
      "asal": "Yogyakarta",
      "tujuan": "Bali",
      "durasi": 105,
      "jarak": 538
    },
    {
      "kode": "ID8370",
      "asal": "Bandung",
      "tujuan": "Yogyakarta",
      "durasi": 153,
      "jarak": 380
    },
    {
      "kode": "GA2169",
      "asal": "Yogyakarta",
      "tujuan": "Lombok",
      "durasi": 265,
      "jarak": 678
    },
    {
      "kode": "ID3080",
      "asal": "Jakarta",
      "tujuan": "Lombok",
      "durasi": 306,
      "jarak": 1067
    },
    {
      "kode": "ID5518",
      "asal": "Lombok",
      "tujuan": "Bali",
      "durasi": 306,
      "jarak": 120
    },
    {
      "kode": "QZ7918",
      "asal": "Yogyakarta",
      "tujuan": "Bali",
      "durasi": 159,
      "jarak": 538
    },
    {
      "kode": "QZ1885",
      "asal": "Bandung",
      "tujuan": "Surabaya",
      "durasi": 91,
      "jarak": 662
    },
    {
      "kode": "QZ2530",
      "asal": "Jakarta",
      "tujuan": "Lombok",
      "durasi": 234,
      "jarak": 1067
    },
    {
      "kode": "JT3037",
      "asal": "Bali",
      "tujuan": "Medan",
      "durasi": 212,
      "jarak": 1975
    },
    {
      "kode": "SJ8305",
      "asal": "Jakarta",
      "tujuan": "Medan",
      "durasi": 250,
      "jarak": 1396
    },
    {
      "kode": "QZ6336",
      "asal": "Medan",
      "tujuan": "Yogyakarta",
      "durasi": 234,
      "jarak": 1915
    },
    {
      "kode": "GA9349",
      "asal": "Lombok",
      "tujuan": "Bali",
      "durasi": 288,
      "jarak": 120
    },
    {
      "kode": "SJ5015",
      "asal": "Makassar",
      "tujuan": "Medan",
      "durasi": 210,
      "jarak": 2474
    },
    {
      "kode": "ID4622",
      "asal": "Makassar",
      "tujuan": "Jakarta",
      "durasi": 84,
      "jarak": 1401
    },
    {
      "kode": "JT4732",
      "asal": "Jakarta",
      "tujuan": "Lombok",
      "durasi": 214,
      "jarak": 1067
    },
    {
      "kode": "GA8186",
      "asal": "Makassar",
      "tujuan": "Surabaya",
      "durasi": 117,
      "jarak": 801
    },
    {
      "kode": "QZ2686",
      "asal": "Bali",
      "tujuan": "Lombok",
      "durasi": 75,
      "jarak": 120
    },
    {
      "kode": "ID8659",
      "asal": "Jakarta",
      "tujuan": "Makassar",
      "durasi": 234,
      "jarak": 1401
    },
    {
      "kode": "JT5308",
      "asal": "Bali",
      "tujuan": "Medan",
      "durasi": 326,
      "jarak": 1975
    },
    {
      "kode": "GA2745",
      "asal": "Surabaya",
      "tujuan": "Medan",
      "durasi": 254,
      "jarak": 1835
    },
    {
      "kode": "JT8371",
      "asal": "Bandung",
      "tujuan": "Surabaya",
      "durasi": 152,
      "jarak": 662
    }
  ]
};
