#!/usr/bin/env python3
"""
KupasAI - Clustering Data Generator
Real flight schedule dataset (Modul 10), K-Means with elbow method.
"""

import json
import os

import pandas as pd
import sklearn.cluster as cls
from sklearn.preprocessing import StandardScaler

HERE = os.path.dirname(os.path.abspath(__file__))

DATASET_DIR = os.environ.get(
    "DASAR_ML_DIR",
    "https://raw.githubusercontent.com/FeliksMakarios/dasar-machine-learning/main",
)


def dataset_path(*parts):
    return "/".join([DATASET_DIR.rstrip("/")] + list(parts))


df1 = pd.read_csv(dataset_path("buku1", "jadwal_penerbangan.csv"))
df2 = df1[["durasi", "jarak"]]

scaler = StandardScaler()
df2_scaled = scaler.fit_transform(df2)

# ---- Elbow method: SSE for k = 1..9 ----
elbow = []
for k in range(1, 10):
    m = cls.KMeans(n_clusters=k, random_state=42, n_init=10)
    m.fit(df2_scaled)
    elbow.append({"k": k, "sse": round(float(m.inertia_), 2)})

# ---- Full clustering results for k = 2, 3, 4, 5 ----
clusterings = {}
for k in [2, 3, 4, 5]:
    m = cls.KMeans(n_clusters=k, random_state=42, n_init=10)
    m.fit(df2_scaled)
    centro = scaler.inverse_transform(m.cluster_centers_)
    labels = m.labels_.tolist()
    counts = [int((m.labels_ == i).sum()) for i in range(k)]
    clusterings[str(k)] = {
        "labels": labels,
        "centroids": [{"durasi": round(float(c[0]), 2), "jarak": round(float(c[1]), 2), "n": counts[i]} for i, c in enumerate(centro)],
    }

flights = []
for _, row in df1.iterrows():
    flights.append({
        "kode": row["kode_penerbangan"],
        "asal": row["asal"],
        "tujuan": row["tujuan"],
        "durasi": int(row["durasi"]),
        "jarak": int(row["jarak"]),
    })

data = {
    "n_flights": int(len(df1)),
    "elbow": elbow,
    "clusterings": clusterings,
    "flights": flights,
}

outpath = os.path.join(HERE, "data.js")
js = "// Auto-generated by generate_clustering_data.py\n"
js += "// Clustering data for KupasAI ML Week 10 - real jadwal_penerbangan.csv (41 rute domestik)\n\n"
js += "const CLUSTER_DATA = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
with open(outpath, "w") as f:
    f.write(js)

print("n_flights:", len(df1))
print("elbow:", elbow)
print("k=3 centroids:", clusterings["3"]["centroids"])
print("Written:", outpath)
